---
jenkinsURLs:
  - https://cloudgpu-ci.amd.com/job/automations/job/entrypoints/job/github-psdb-entrypoint/
  - https://cvs-ci.amd.com/job/automations/job/entrypoints/job/github-psdb-entrypoint/
skipDrafts: true
help:
  doc: >-
    https://amd.atlassian.net/wiki/display/SI/Pre-Submit+job+using+GitHub+in+Jenkins
  enabled: true
  includeTriggers: true
  verbose: false
  message: >-
    This branch is configured to trigger PSDB. Comment __!help__ to get more details
triggerExclusions:
  all:
    - "psdb-jenkins-trigger-dev[bot]"
    - "psdb-jenkins-trigger[bot]"
  onEdit:
    - "swjenci"
branches:
  - branchName: "dev"
    help:
      enabled: true
      message: >-
        The expectation is that your final commit gets run with a passing __!psdb__ trigger
    triggers:
      - triggerName: "!psdb"
        description: Check HyperV and KVM presubmission builds can pass
        onOpen: true
        onSynchronize: false
        jobs:
          - "[jenkins-psdb, Opensource-MxGPU-psdb]"
          - "[jenkins-psdb, mxgpu_dev-psdb]"
      - triggerName: "!psdb-hyperv"
        description: Check only HyperV presubmission build can pass
        onOpen: true
        onSynchronize: false
        jobs:
          - "[jenkins-psdb, mxgpu_dev-psdb]"
      - triggerName: "!psdb-kvm"
        description: Check only KVM presubmission build can pass
        onOpen: true
        onSynchronize: false
        jobs:
          - "[jenkins-psdb, Opensource-MxGPU-psdb]"
