# Copyright Advanced Micro Devices, Inc.
#
# SPDX-License-Identifier: MIT

LIBGV_HW_NAVI3_FILES = \
	navi32_reg_init.o \
	navi32_ip_discovery.o  \
	navi32_mem.o \
	navi32_mailbox.o  \
	navi32_irqmgr.o \
	umc_v8_10.o \
	df_v4_3.o \
	navi32_ecc.o \
	navi32_gpumon.o \
	navi32_device.o \
	navi32_mmsch.o \
	navi32_psp.o  \
	navi32_sched.o \
	navi32_clockgating.o \
	navi32_misc.o  \
	navi32_gfx.o  \
	navi32_sdma.o \
	navi32_ucode.o \
	navi32_gc.o \
	navi32_vbios.o \
	navi32_gpuiov.o \
	navi32_reset.o \
	navi32_powerplay.o \
	navi32_fru.o \
	navi32_ffbm.o \
	navi32_diag_data.o \
	navi32_diag_data_reg.o \
	navi32_vcn.o \
	navi32_nbio.o \
	gfx_v11_0.o \
	navi32_dirtybit.o \
	mmhub_v3_0.o
