#
# Copyright (c) 2021 Advanced Micro Devices, Inc. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE

LIBGV_HW_NAVI3_PATH = $(LIBGV_CORE_PATH)/hw/navi3

LIBGV_HW_NAVI3_LOCAL = \
	navi32_reg_init.o \
	navi32_ip_discovery.o  \
	navi32_mem.o \
	navi32_mailbox.o  \
	navi32_irqmgr.o \
	umc_v8_10.o \
	df_v4_3.o \
	navi32_ecc.o \
	navi32_gpumon.o \
	navi32_device.o \
	navi32_mmsch.o \
	navi32_psp.o  \
	navi32_sched.o \
	navi32_clockgating.o \
	navi32_misc.o  \
	navi32_gfx.o  \
	navi32_sdma.o \
	navi32_ucode.o \
	navi32_gc.o \
	navi32_vbios.o \
	navi32_gpuiov.o \
	navi32_reset.o \
	navi32_powerplay.o \
	navi32_fru.o \
	navi32_ffbm.o \
	navi32_diag_data.o \
	navi32_diag_data_reg.o \
	navi32_vcn.o \
	navi32_nbio.o \
	gfx_v11_0.o \
	navi32_dirtybit.o \
	mmhub_v3_0.o

LIBGV_HW_NAVI3_FILES = $(addprefix core/hw/navi3/,$(LIBGV_HW_NAVI3_LOCAL))

