# Copyright Advanced Micro Devices, Inc.
#
# SPDX-License-Identifier: MIT

gim-y += gim_shim/gim_drv.o
gim-y += gim_shim/gim_os_service.o
gim-y += gim_shim/gim_config.o
gim-y += gim_shim/gim_gpumon.o
gim-y += gim_shim/gim_error.o
gim-y += gim_shim/gim_live_update.o
gim-y += gim_shim/gim_hbm_dax.o
gim-y += gim_shim/gim_hbm_drv_mgmt.o
gim-y += gim_shim/gim_ftrace.o
gim-y += gim_shim/gim_baco_power_saving.o
gim-y += gim_shim/gim_memory_sentinel.o
gim-y += gim_shim/gim_iova_sys_mem.o
gim-y += gim_shim/gim_mig.o
gim-y += gim_shim/dcore_drv.o

gim-y += gim_shim/sysfs/gim_sysfs_emit.o
gim-y += gim_shim/sysfs/gim_monitor.o
gim-y += gim_shim/sysfs/gim_guard.o
gim-y += gim_shim/sysfs/gim_debugfs.o
gim-y += gim_shim/sysfs/amdgv_cmd.o
gim-y += gim_shim/sysfs/amdgv_uniras_cmd.o
