#
# Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE

gim-y += gim_shim/gim_drv.o
gim-y += gim_shim/gim_os_service.o
gim-y += gim_shim/gim_config.o
gim-y += gim_shim/gim_gpumon.o
gim-y += gim_shim/gim_error.o
gim-y += gim_shim/gim_live_update.o
gim-y += gim_shim/gim_ftrace.o
gim-y += gim_shim/gim_baco_power_saving.o
gim-y += gim_shim/gim_memory_sentinel.o
gim-y += gim_shim/gim_iova_sys_mem.o
gim-y += gim_shim/gim_mig.o
gim-y += gim_shim/dcore_drv.o

gim-y += gim_shim/sysfs/gim_sysfs_emit.o
gim-y += gim_shim/sysfs/gim_monitor.o
gim-y += gim_shim/sysfs/gim_guard.o
gim-y += gim_shim/sysfs/gim_debugfs.o
gim-y += gim_shim/sysfs/amdgv_cmd.o
gim-y += gim_shim/sysfs/amdgv_uniras_cmd.o
