#
# Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE

LIBGV_PATH = $(src)/../libgv
GIM_SHIM_PATH = $(src)/gim_shim

SMI_LIB_PATH=$(src)/../smi-lib
SMI_DRV_PATH = $(SMI_LIB_PATH)/drv

GIM_COMS_PATH = $(src)/../gim-coms-lib

subdir-ccflags-y += -I$(GIM_SHIM_PATH) -I$(GIM_SHIM_PATH)/sysfs
subdir-ccflags-y += -I$(SMI_DRV_PATH)/inc -I$(SMI_DRV_PATH)/linux -I$(SMI_LIB_PATH)/inc/common
subdir-ccflags-y += -I$(GIM_COMS_PATH)/inc
subdir-ccflags-y += -I$(src)/inc
subdir-ccflags-y += -include $(src)/dkms/config.h
subdir-ccflags-y += -Werror -Wimplicit-fallthrough=2 -Wno-enum-conversion -Wno-expansion-to-defined

include $(GIM_SHIM_PATH)/Kbuild

include $(LIBGV_PATH)/Makefile
gim-y += $(addprefix ../libgv/,$(LIBGV_COMPILE_FILES))
subdir-ccflags-y += $(LIBGV_CCFLAGS)

include $(SMI_DRV_PATH)/Makefile
gim-y += $(addprefix ../smi-lib/drv/,$(SMI_COMPILE_FILES))

obj-m += amd-vfio-pci/
obj-m += gim.o
