/* Copyright Advanced Micro Devices, Inc.
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef SMU_V15_0_8_PP_H
#define SMU_V15_0_8_PP_H

#include "amdgv_powerplay_swsmu.h"
#include "amdgv_gpumon.h"

#define max(a, b)		((a) > (b) ? (a) : (b))
#define MAX_NUM_METRICS		255

#define SMU_15_GPU_RES_ID	0
#define SMU_15_NUM_AID		2
#define SMU_15_NUM_MID		2
#define SMU_15_NUM_XCD		8
#define SMU_15_JPEG_PER_MID	20
#define SMU_15_SMU_NUM_HBM	12
#define SMU_15_HBM_PER_AID	6

enum metric_addr_encoding {
	UINT32_BIT0 = 0,
	UINT32_BIT1 = 1,
	UINT32_BIT2 = 2,
	UINT32_BIT3 = 3,
	UINT32_BIT4 = 4,
	UINT32_BIT5 = 5,
	UINT32_BIT6 = 6,
	UINT32_BIT7 = 7,
	UINT_16,
	UINT_32,
	UINT_64,
	Q10_32,
	Q10_32_DS,
	Q10_64,
	INT_16,
	NOT_AVAILABLE
};

enum smu_15_metric_name {
	/* GPU */
	SMU_15_METRICS_COUNTER,
	SMU_15_GFX_CLK_XCD,

	SMU_15_GFX_CLK_DS_XCD,
	// SMU_15_GFX_CLK_LOCKED_XCD,
	SMU_15_SOC_CLK,
	SMU_15_SOC_CLK_DS,
	SMU_15_VCLK,
	SMU_15_VCLK_DS,
	SMU_15_DCLK,
	SMU_15_DCLK_DS,
	SMU_15_MEMCLK,

	SMU_15_MEM_CLK_DS,
	SMU_15_GFX_CLK_XCD_ACC,
	SMU_15_USAGE_GFX_XCD,
	SMU_15_USAGE_GFX,
	SMU_15_USAGE_MEM,
	SMU_15_USAGE_JPEG,
	SMU_15_USAGE_VCN,
	SMU_15_DRAM_BANDWIDTH_MAX,
	SMU_15_USAGE_GFX_XCD_ACC,
	SMU_15_USAGE_GFX_ACC,
	SMU_15_USAGE_MEM_ACC,
	SMU_15_DRAM_BANDWIDTH_ACC,
	SMU_15_TEMP_HOTSPOT,
	SMU_15_TEMP_VR,
	// SMU_15_TEMP_MEM,
	SMU_15_TEMP_HOTSPOT_ACC,
	SMU_15_TEMP_VR_ACC,
	// SMU_15_TEMP_MEM_ACC,
	SMU_15_POWER_MAX,
	SMU_15_POWER,
	SMU_15_ENERGY_SOCKET_ACC,
	// SMU_15_ENERGY_XCD_ACC,
	// SMU_15_ENERGY_AID_ACC,
	SMU_15_ENERGY_MEM_ACC,
	SMU_15_THROT_GFX_BEL_PPT_ACC,
	SMU_15_THROT_GFX_BEL_THM_ACC,
	SMU_15_THROT_GFX_BEL_TOT_ACC,
	SMU_15_THROT_GFX_CLK_LOW_ACC,
	SMU_15_THROT_PROCHOT_ACC,
	SMU_15_THROT_PPT_ACC,
	SMU_15_THROT_SOCKET_ACC,
	SMU_15_THROT_VR_ACC,
	SMU_15_THROT_MEM_ACC,
	SMU_15_PCIE_LINK_SPEED,
	SMU_15_PCIE_LINK_WIDTH,
	SMU_15_PCIE_BANDWIDTH,
	SMU_15_PCIE_BANDWIDTH_ACC,
	SMU_15_PCIE_L0_TO_RECOVER_ACC,
	SMU_15_PCIE_REPL_ACC,
	SMU_15_PCIE_REPL_ROLLOVER_ACC,
	SMU_15_PCIE_NAK_SENT_ACC,
	SMU_15_PCIE_NAK_RECEIVED_ACC,

	SMU_15_TEMP_XCD,
	SMU_15_TEMP_HBM,
	SMU_15_TEMP_HBM_ACC,
	SMU_15_TEMP_AID,
	SMU_15_TEMP_MID,
	SMU_15_FCLK,
	SMU_15_FCLK_DS,
	SMU_15_LCLK,
	SMU_15_LCLK_DS,
	SMU_15_PCIE_OTHER_END_RECOVERY_ACC,

	/* GPU Static */
	SMU_15_GFX_CLK_MAX,
	SMU_15_GFX_CLK_MIN,
	SMU_15_FCLK_MAX,
	SMU_15_FCLK_MIN,
	SMU_15_GL2CLK_MAX,
	SMU_15_GL2CLK_MIN,
	SMU_15_MEMCLK_MAX,
	SMU_15_MEMCLK_MIN,
	SMU_15_POWER_STATIC,

	// SMU_15_SOC_CLK_MAX,		// Missing?
	// SMU_15_SOC_CLK_MIN,		// Missing?
	// SMU_15_VCLK_MAX,		// Missing?
	// SMU_15_VCLK_MIN,		// Missing?
	// SMU_15_DCLK_MAX,		// Missing?
	// SMU_15_DCLK_MIN,		// Missing?
	// SMU_15_LCLK_MAX,		// Missing?
	// SMU_15_LCLK_MIN,		// Missing?

	SMU_15_CTF_XCD,
	SMU_15_CTF_AID,
	SMU_15_CTF_MID,
	SMU_15_CTF_HBM,
	SMU_15_THROTTLE_XCD,
	SMU_15_THROTTLE_AID,
	SMU_15_THROTTLE_MID,
	SMU_15_THROTTLE_HBM,

	SMU_15_IN_TEL_VOLTAGE,
	SMU_15_PLDM_VERSION,

	/* System */
	SMU_15_SYS_METRIC_ACC_COUNTER,
	SMU_15_SYSTEM_TEMP_UBB_FPGA,
	SMU_15_SYSTEM_TEMP_UBB_FRONT,
	SMU_15_SYSTEM_TEMP_UBB_BACK,
	SMU_15_SYSTEM_TEMP_UBB_OAM7,
	SMU_15_SYSTEM_TEMP_UBB_IBC,
	SMU_15_SYSTEM_TEMP_UBB_UFPGA,
	SMU_15_SYSTEM_TEMP_UBB_OAM1,
	SMU_15_SYSTEM_TEMP_OAM_0_1_HSC,
	SMU_15_SYSTEM_TEMP_OAM_2_3_HSC,
	SMU_15_SYSTEM_TEMP_OAM_4_5_HSC,
	SMU_15_SYSTEM_TEMP_OAM_6_7_HSC,
	SMU_15_SYSTEM_TEMP_UBB_FPGA_0V72_VR,
	SMU_15_SYSTEM_TEMP_UBB_FPGA_3V3_VR,
	SMU_15_SYSTEM_TEMP_RETIMER_0_1_2_3_1V2_VR,
	SMU_15_SYSTEM_TEMP_RETIMER_4_5_6_7_1V2_VR,
	SMU_15_SYSTEM_TEMP_RETIMER_0_1_0V9_VR,
	SMU_15_SYSTEM_TEMP_RETIMER_4_5_0V9_VR,
	SMU_15_SYSTEM_TEMP_RETIMER_2_3_0V9_VR,
	SMU_15_SYSTEM_TEMP_RETIMER_6_7_0V9_VR,
	SMU_15_SYSTEM_TEMP_OAM_0_1_2_3_3V3_VR,
	SMU_15_SYSTEM_TEMP_OAM_4_5_6_7_3V3_VR,
	SMU_15_SYSTEM_TEMP_IBC_HSC,
	SMU_15_SYSTEM_TEMP_IBC,
	SMU_15_NODE_TEMP_RETIMER,
	SMU_15_NODE_TEMP_IBC_TEMP,
	SMU_15_NODE_TEMP_IBC_2_TEMP,
	SMU_15_NODE_TEMP_VDD18_VR_TEMP,
	SMU_15_NODE_TEMP_04_HBM_B_VR_TEMP,
	SMU_15_NODE_TEMP_04_HBM_D_VR_TEMP,
	SMU_15_SVI_PLANE_VDDCR_X0_TEMP,
	SMU_15_SVI_PLANE_VDDCR_X1_TEMP,
	SMU_15_SVI_PLANE_VDDIO_HBM_B_TEMP,
	SMU_15_SVI_PLANE_VDDIO_HBM_D_TEMP,
	SMU_15_SVI_PLANE_VDDIO_04_HBM_B_TEMP,
	SMU_15_SVI_PLANE_VDDIO_04_HBM_D_TEMP,
	SMU_15_SVI_PLANE_VDDCR_HBM_B_TEMP,
	SMU_15_SVI_PLANE_VDDCR_HBM_D_TEMP,
	SMU_15_SVI_PLANE_VDDCR_075_HBM_B_TEMP,
	SMU_15_SVI_PLANE_VDDCR_075_HBM_D_TEMP,
	SMU_15_SVI_PLANE_VDDIO_11_GTA_A_TEMP,
	SMU_15_SVI_PLANE_VDDIO_11_GTA_C_TEMP,
	SMU_15_SVI_PLANE_VDDAN_075_GTA_A_TEMP,
	SMU_15_SVI_PLANE_VDDAN_075_GTA_C_TEMP,
	SMU_15_SVI_PLANE_VDDCR_075_UCIE_TEMP,
	SMU_15_SVI_PLANE_VDDIO_065_UCIEAA_TEMP,
	SMU_15_SVI_PLANE_VDDIO_065_UCIEAM_A_TEMP,
	SMU_15_SVI_PLANE_VDDIO_065_UCIEAM_C_TEMP,
	SMU_15_SVI_PLANE_VDDCR_SOCIO_A_TEMP,
	SMU_15_SVI_PLANE_VDDCR_SOCIO_C_TEMP,
	SMU_15_SVI_PLANE_VDDAN_075_TEMP,
	SMU_15_SYSTEM_POWER_UBB_POWER,
	SMU_15_SYSTEM_POWER_UBB_POWER_THRESHOLD,

	SMU_15_METRIC_NAME_COUNT,
};

uint64_t metric_code[SMU_15_METRIC_NAME_COUNT] = {
	/*					CATEGORY				NAME					UNIT			RES  SUBRES		FLAGS	*/
	/* GPU Metrics */
	[SMU_15_METRICS_COUNTER]		= METRIC_EXT_CODE(ACC_COUNTER,		METRIC_ACC_COUNTER,			COUNTER,		GPU, NA,		METRIC_EXT_FLAG(COUNTER)),

	[SMU_15_GFX_CLK_XCD]			= METRIC_EXT_CODE(FREQUENCY,		CLK_GFX,				MHZ,			XCP,	XCC,		METRIC_EXT_FLAG(DATA_FILTER_INST) | METRIC_EXT_FLAG(CHIPLET_METRIC)),
	[SMU_15_GFX_CLK_DS_XCD]			= METRIC_EXT_CODE(FREQUENCY,		CLK_GFX_DS_DISABLED,			BOOL,			XCP,	XCC,		METRIC_EXT_FLAG(DATA_FILTER_INST) | METRIC_EXT_FLAG(CHIPLET_METRIC)),
	[SMU_15_USAGE_GFX_XCD]			= METRIC_EXT_CODE(ACTIVITY,		USAGE_GFX,				PERCENT,		XCP,	XCC,		METRIC_EXT_FLAG(DATA_FILTER_INST) | METRIC_EXT_FLAG(CHIPLET_METRIC)),
	[SMU_15_TEMP_XCD]			= METRIC_EXT_CODE(TEMPERATURE,		TEMP_XCD,				CELSIUS,		XCP,	XCC,		METRIC_EXT_FLAG(DATA_FILTER_INST) | METRIC_EXT_FLAG(CHIPLET_METRIC)),

	[SMU_15_GFX_CLK_XCD_ACC]		= METRIC_EXT_CODE(FREQUENCY,		CLK_GFX,				MHZ,			XCP,	XCC,		METRIC_EXT_FLAG(DATA_FILTER_ACC)  | METRIC_EXT_FLAG(CHIPLET_METRIC)),
	[SMU_15_USAGE_GFX_XCD_ACC]		= METRIC_EXT_CODE(ACTIVITY,		USAGE_GFX,				PERCENT,		XCP,	XCC,		METRIC_EXT_FLAG(DATA_FILTER_ACC)  | METRIC_EXT_FLAG(CHIPLET_METRIC)),
	[SMU_15_THROT_GFX_BEL_PPT_ACC]		= METRIC_EXT_CODE(THROTTLE,		GFX_CLK_BELOW_HOST_LIMIT_PPT,		BOOL,			XCP,	XCC,		METRIC_EXT_FLAG(DATA_FILTER_ACC)  | METRIC_EXT_FLAG(CHIPLET_METRIC)),
	[SMU_15_THROT_GFX_BEL_THM_ACC]		= METRIC_EXT_CODE(THROTTLE,		GFX_CLK_BELOW_HOST_LIMIT_THM,		BOOL,			XCP,	XCC,		METRIC_EXT_FLAG(DATA_FILTER_ACC)  | METRIC_EXT_FLAG(CHIPLET_METRIC)),
	[SMU_15_THROT_GFX_BEL_TOT_ACC]		= METRIC_EXT_CODE(THROTTLE,		GFX_CLK_BELOW_HOST_LIMIT_TOTAL,		BOOL,			XCP,	XCC,		METRIC_EXT_FLAG(DATA_FILTER_ACC)  | METRIC_EXT_FLAG(CHIPLET_METRIC)),
	[SMU_15_THROT_GFX_CLK_LOW_ACC]		= METRIC_EXT_CODE(THROTTLE,		GFX_CLK_LOW_UTILIZATION,		BOOL,			XCP,	XCC,		METRIC_EXT_FLAG(DATA_FILTER_ACC)  | METRIC_EXT_FLAG(CHIPLET_METRIC)),

	[SMU_15_SOC_CLK]			= METRIC_EXT_CODE(FREQUENCY,		CLK_SOC,				MHZ, 			MID,	NA,		METRIC_EXT_FLAG(DATA_FILTER_INST) | METRIC_EXT_FLAG(CHIPLET_METRIC)),
	[SMU_15_SOC_CLK_DS]			= METRIC_EXT_CODE(FREQUENCY,		CLK_SOC_DS_DISABLED,			BOOL,			MID,	NA,		METRIC_EXT_FLAG(DATA_FILTER_INST) | METRIC_EXT_FLAG(CHIPLET_METRIC)),
	[SMU_15_VCLK]				= METRIC_EXT_CODE(FREQUENCY,		CLK_VCLK,				MHZ,			MID,	NA,		METRIC_EXT_FLAG(DATA_FILTER_INST) | METRIC_EXT_FLAG(CHIPLET_METRIC)),
	[SMU_15_VCLK_DS]			= METRIC_EXT_CODE(FREQUENCY,		CLK_VCLK_DS_DISABLED,			BOOL,			MID,	NA,		METRIC_EXT_FLAG(DATA_FILTER_INST) | METRIC_EXT_FLAG(CHIPLET_METRIC)),
	[SMU_15_DCLK]				= METRIC_EXT_CODE(FREQUENCY,		CLK_DCLK,				MHZ,			MID,	NA,		METRIC_EXT_FLAG(DATA_FILTER_INST) | METRIC_EXT_FLAG(CHIPLET_METRIC)),
	[SMU_15_DCLK_DS]			= METRIC_EXT_CODE(FREQUENCY,		CLK_DCLK_DS_DISABLED,			BOOL,			MID,	NA,		METRIC_EXT_FLAG(DATA_FILTER_INST) | METRIC_EXT_FLAG(CHIPLET_METRIC)),
	[SMU_15_LCLK]				= METRIC_EXT_CODE(FREQUENCY,		CLK_LCLK,				MHZ,			MID,	NA,		METRIC_EXT_FLAG(DATA_FILTER_INST) | METRIC_EXT_FLAG(CHIPLET_METRIC)),
	[SMU_15_LCLK_DS]			= METRIC_EXT_CODE(FREQUENCY,		CLK_LCLK_DS_DISABLED,			BOOL,			MID,	NA,		METRIC_EXT_FLAG(DATA_FILTER_INST) | METRIC_EXT_FLAG(CHIPLET_METRIC)),


	[SMU_15_USAGE_JPEG]			= METRIC_EXT_CODE(ACTIVITY,		USAGE_JPEG,				PERCENT,		MID,	ENGINE,		METRIC_EXT_FLAG(DATA_FILTER_INST) | METRIC_EXT_FLAG(CHIPLET_METRIC)),
	[SMU_15_USAGE_VCN]			= METRIC_EXT_CODE(ACTIVITY,		USAGE_VCN,				PERCENT,		MID,	ENGINE,		METRIC_EXT_FLAG(DATA_FILTER_INST) | METRIC_EXT_FLAG(CHIPLET_METRIC)),

	[SMU_15_TEMP_MID]			= METRIC_EXT_CODE(TEMPERATURE,		TEMP_MID,				CELSIUS,		MID,	NA,		METRIC_EXT_FLAG(DATA_FILTER_INST) | METRIC_EXT_FLAG(CHIPLET_METRIC)),

	[SMU_15_TEMP_HBM]			= METRIC_EXT_CODE(TEMPERATURE,		TEMP_MEM_CURR,				CELSIUS,		AID,	HBM,		METRIC_EXT_FLAG(DATA_FILTER_INST) | METRIC_EXT_FLAG(CHIPLET_METRIC)),
	[SMU_15_TEMP_AID]			= METRIC_EXT_CODE(TEMPERATURE,		TEMP_AID,				CELSIUS,		AID,	NA,		METRIC_EXT_FLAG(DATA_FILTER_INST) | METRIC_EXT_FLAG(CHIPLET_METRIC)),
	[SMU_15_MEMCLK]				= METRIC_EXT_CODE(FREQUENCY,		CLK_MEM,				MHZ,			AID,	NA,		METRIC_EXT_FLAG(DATA_FILTER_INST) | METRIC_EXT_FLAG(CHIPLET_METRIC)),
	[SMU_15_MEM_CLK_DS]			= METRIC_EXT_CODE(FREQUENCY,		CLK_MEM_DS_DISABLED,			BOOL,			AID,	NA,		METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_FCLK]				= METRIC_EXT_CODE(FREQUENCY,		CLK_FCLK,				MHZ,			AID,	NA,		METRIC_EXT_FLAG(DATA_FILTER_INST) | METRIC_EXT_FLAG(CHIPLET_METRIC)),
	[SMU_15_FCLK_DS]			= METRIC_EXT_CODE(FREQUENCY,		CLK_FCLK_DS_DISABLED,			BOOL,			AID,	NA,		METRIC_EXT_FLAG(DATA_FILTER_INST) | METRIC_EXT_FLAG(CHIPLET_METRIC)),
	[SMU_15_TEMP_HBM_ACC]			= METRIC_EXT_CODE(TEMPERATURE,		TEMP_MEM_CURR,				CELSIUS,		AID,	HBM,		METRIC_EXT_FLAG(DATA_FILTER_ACC) | METRIC_EXT_FLAG(CHIPLET_METRIC)),

	[SMU_15_USAGE_GFX]			= METRIC_EXT_CODE(ACTIVITY,		USAGE_GFX,				PERCENT,		GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_USAGE_MEM]			= METRIC_EXT_CODE(ACTIVITY,		USAGE_MEM,				PERCENT,		GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_DRAM_BANDWIDTH_MAX]		= METRIC_EXT_CODE(ACTIVITY,		MAX_DRAM_BANDWIDTH,			GBPS,			GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_TEMP_HOTSPOT]			= METRIC_EXT_CODE(TEMPERATURE,		TEMP_HOTSPOT_CURR,			CELSIUS,		GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_TEMP_VR]			= METRIC_EXT_CODE(TEMPERATURE,		TEMP_VR_CURR,				CELSIUS,		GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_POWER_MAX]			= METRIC_EXT_CODE(POWER,		POWER_LIMIT,				WATT,			GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_POWER]				= METRIC_EXT_CODE(POWER,		POWER_CURR,				WATT,			GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_PCIE_LINK_SPEED]		= METRIC_EXT_CODE(PCIE,			PCIE_LINK_SPEED,			PCIE_GEN,		GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_PCIE_LINK_WIDTH]		= METRIC_EXT_CODE(PCIE,			PCIE_LINK_WIDTH,			PCIE_LANES,		GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_PCIE_BANDWIDTH]			= METRIC_EXT_CODE(PCIE,			PCIE_BANDWIDTH,				MBITPS,			GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_INST)),

	[SMU_15_USAGE_GFX_ACC]			= METRIC_EXT_CODE(ACTIVITY,		USAGE_GFX,				PERCENT,		GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_ACC)),
	[SMU_15_USAGE_MEM_ACC]			= METRIC_EXT_CODE(ACTIVITY,		USAGE_MEM,				PERCENT,		GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_ACC)),
	[SMU_15_DRAM_BANDWIDTH_ACC]		= METRIC_EXT_CODE(ACTIVITY,		DRAM_BANDWIDTH,				GBPS,			GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_ACC)),
	[SMU_15_TEMP_HOTSPOT_ACC]		= METRIC_EXT_CODE(TEMPERATURE,		TEMP_HOTSPOT_CURR,			CELSIUS,		GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_ACC)),
	[SMU_15_TEMP_VR_ACC]			= METRIC_EXT_CODE(TEMPERATURE,		TEMP_VR_CURR,				CELSIUS,		GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_ACC)),
	[SMU_15_ENERGY_SOCKET_ACC]		= METRIC_EXT_CODE(ENERGY,		ENERGY_SOCKET,				15_625_MILLIJOULE,	GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_ACC)),
	[SMU_15_ENERGY_MEM_ACC]			= METRIC_EXT_CODE(ENERGY,		ENERGY_MEM,				15_625_MILLIJOULE,	GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_ACC)),
	[SMU_15_THROT_PROCHOT_ACC]		= METRIC_EXT_CODE(THROTTLE,		THROTTLE_PROCHOT_ACTIVE,		BOOL,			GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_ACC)),
	[SMU_15_THROT_PPT_ACC]			= METRIC_EXT_CODE(THROTTLE,		THROTTLE_PPT_ACTIVE,			BOOL,			GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_ACC)),
	[SMU_15_THROT_SOCKET_ACC]		= METRIC_EXT_CODE(THROTTLE,		THROTTLE_SOCKET_ACTIVE,			BOOL,			GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_ACC)),
	[SMU_15_THROT_VR_ACC]			= METRIC_EXT_CODE(THROTTLE,		THROTTLE_VR_ACTIVE,			BOOL,			GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_ACC)),
	[SMU_15_THROT_MEM_ACC]			= METRIC_EXT_CODE(THROTTLE,		THROTTLE_MEM_ACTIVE,			BOOL,			GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_ACC)),
	[SMU_15_PCIE_BANDWIDTH_ACC]		= METRIC_EXT_CODE(PCIE,			PCIE_BANDWIDTH,				GBPS,			GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_ACC)),
	[SMU_15_PCIE_L0_TO_RECOVER_ACC]		= METRIC_EXT_CODE(PCIE,			PCIE_L0_TO_RECOVERY_COUNT,		UINT,			GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_ACC)),
	[SMU_15_PCIE_REPL_ACC]			= METRIC_EXT_CODE(PCIE,			PCIE_REPLAY_COUNT,			UINT,			GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_ACC)),
	[SMU_15_PCIE_REPL_ROLLOVER_ACC]		= METRIC_EXT_CODE(PCIE,			PCIE_REPLAY_ROLLOVER_COUNT,		UINT,			GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_ACC)),
	[SMU_15_PCIE_NAK_SENT_ACC]		= METRIC_EXT_CODE(PCIE,			PCIE_NAK_SENT_COUNT,			UINT,			GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_ACC)),
	[SMU_15_PCIE_NAK_RECEIVED_ACC]		= METRIC_EXT_CODE(PCIE,			PCIE_NAK_RECEIVED_COUNT,		UINT,			GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_ACC)),
	[SMU_15_PCIE_OTHER_END_RECOVERY_ACC]	= METRIC_EXT_CODE(PCIE,			PCIE_OTHER_END_RECOVERY_COUNT,		UINT,			GPU,	NA,		METRIC_EXT_FLAG(DATA_FILTER_ACC)),

	/* GPU Static metrics */
	[SMU_15_GFX_CLK_MAX]			= METRIC_EXT_CODE(STATIC_FREQUENCY,	CLK_GFX_MAX_LIMIT,			MHZ,			GPU,	NA,		0),
	[SMU_15_GFX_CLK_MIN]			= METRIC_EXT_CODE(STATIC_FREQUENCY,	CLK_GFX_MIN_LIMIT,			MHZ,			GPU,	NA,		0),
	[SMU_15_FCLK_MAX]			= METRIC_EXT_CODE(STATIC_FREQUENCY,	CLK_FCLK_MAX_LIMIT,			MHZ,			GPU,	NA,		0),
	[SMU_15_FCLK_MIN]			= METRIC_EXT_CODE(STATIC_FREQUENCY,	CLK_FCLK_MIN_LIMIT,			MHZ,			GPU,	NA,		0),
	[SMU_15_MEMCLK_MAX]			= METRIC_EXT_CODE(STATIC_FREQUENCY,	CLK_MEM_MAX_LIMIT,			MHZ,			GPU,	NA,		0),
	[SMU_15_MEMCLK_MIN]			= METRIC_EXT_CODE(STATIC_FREQUENCY,	CLK_MEM_MIN_LIMIT,			MHZ,			GPU,	NA,		0),

	// @TODO: Missing?
//	[SMU_15_GL2CLK_MAX]			= METRIC_EXT_CODE(FREQUENCY,		CLK_FCLK_MAX_LIMIT,			MHZ,			GPU,	NA,		0),
//	[SMU_15_GL2CLK_MIN]			= METRIC_EXT_CODE(FREQUENCY,		CLK_FCLK_MIN_LIMIT,			MHZ,			GPU,	NA,		0),
//	[SMU_15_SOC_CLK_MAX]			= METRIC_EXT_CODE(FREQUENCY,		CLK_SOC_MAX_LIMIT,			MHZ,			GPU,	NA,		0),
//	[SMU_15_SOC_CLK_MIN]			= METRIC_EXT_CODE(FREQUENCY,		CLK_SOC_MIN_LIMIT,			MHZ,			GPU,	NA,		0),
//	[SMU_15_VCLK_MAX]			= METRIC_EXT_CODE(FREQUENCY,		CLK_VCLK_MAX_LIMIT,			MHZ,			GPU,	NA,		0),
//	[SMU_15_VCLK_MIN]			= METRIC_EXT_CODE(FREQUENCY,		CLK_VCLK_MIN_LIMIT,			MHZ,			GPU,	NA,		0),
//	[SMU_15_DCLK_MAX]			= METRIC_EXT_CODE(FREQUENCY,		CLK_DCLK_MAX_LIMIT,			MHZ,			GPU,	NA,		0),
//	[SMU_15_DCLK_MIN]			= METRIC_EXT_CODE(FREQUENCY,		CLK_DCLK_MIN_LIMIT,			MHZ,			GPU,	NA,		0),


	[SMU_15_IN_TEL_VOLTAGE]			= METRIC_EXT_CODE(STATIC,		INPUT_TELEMETRY_VOLTAGE,		MILLIVOLT,		GPU,	NA,		0),
	[SMU_15_PLDM_VERSION]			= METRIC_EXT_CODE(STATIC,		PLDM_VERSION,				UINT,			GPU,	NA,		0),

	[SMU_15_CTF_XCD]			= METRIC_EXT_CODE(STATIC_TEMPERATURE,	TEMP_SHUTDOWN_XCD,			CELSIUS,		GPU,	NA,		0),
	[SMU_15_CTF_AID]			= METRIC_EXT_CODE(STATIC_TEMPERATURE,	TEMP_SHUTDOWN_AID,			CELSIUS,		GPU,	NA,		0),
	[SMU_15_CTF_MID]			= METRIC_EXT_CODE(STATIC_TEMPERATURE,	TEMP_SHUTDOWN_MID,			CELSIUS,		GPU,	NA,		0),
	[SMU_15_CTF_HBM]			= METRIC_EXT_CODE(STATIC_TEMPERATURE,	TEMP_SHUTDOWN_HBM,			CELSIUS,		GPU,	NA,		0),

	[SMU_15_THROTTLE_XCD]			= METRIC_EXT_CODE(STATIC_THROTTLE,	TEMP_SHUTDOWN_XCD,			CELSIUS,		GPU,	NA,		0),
	[SMU_15_THROTTLE_AID]			= METRIC_EXT_CODE(STATIC_THROTTLE,	TEMP_SHUTDOWN_AID,			CELSIUS,		GPU,	NA,		0),
	[SMU_15_THROTTLE_MID]			= METRIC_EXT_CODE(STATIC_THROTTLE,	TEMP_SHUTDOWN_MID,			CELSIUS,		GPU,	NA,		0),
	[SMU_15_THROTTLE_HBM]			= METRIC_EXT_CODE(STATIC_THROTTLE,	TEMP_SHUTDOWN_HBM,			CELSIUS,		GPU,	NA,		0),

	/* System metrics */

	[SMU_15_SYS_METRIC_ACC_COUNTER]			= METRIC_EXT_CODE(SYS_ACC_COUNTER,	SYS_METRIC_ACC_COUNTER,			COUNTER,		SYSTEM,	NA,		METRIC_EXT_FLAG(COUNTER)),
	[SMU_15_SYSTEM_TEMP_UBB_FPGA]			= METRIC_EXT_CODE(SYS_BASEBOARD_TEMP,	SYSTEM_TEMP_UBB_FPGA,			CELSIUS,		SYSTEM,	BASEBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SYSTEM_TEMP_UBB_FRONT]			= METRIC_EXT_CODE(SYS_BASEBOARD_TEMP,	SYSTEM_TEMP_UBB_FRONT,			CELSIUS,		SYSTEM,	BASEBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SYSTEM_TEMP_UBB_BACK]			= METRIC_EXT_CODE(SYS_BASEBOARD_TEMP,	SYSTEM_TEMP_UBB_BACK,			CELSIUS,		SYSTEM,	BASEBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SYSTEM_TEMP_UBB_OAM7]			= METRIC_EXT_CODE(SYS_BASEBOARD_TEMP,	SYSTEM_TEMP_UBB_OAM7,			CELSIUS,		SYSTEM,	BASEBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SYSTEM_TEMP_UBB_IBC]			= METRIC_EXT_CODE(SYS_BASEBOARD_TEMP,	SYSTEM_TEMP_UBB_IBC,			CELSIUS,		SYSTEM,	BASEBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SYSTEM_TEMP_UBB_UFPGA]			= METRIC_EXT_CODE(SYS_BASEBOARD_TEMP,	SYSTEM_TEMP_UBB_UFPGA,			CELSIUS,		SYSTEM,	BASEBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SYSTEM_TEMP_UBB_OAM1]			= METRIC_EXT_CODE(SYS_BASEBOARD_TEMP,	SYSTEM_TEMP_UBB_OAM1,			CELSIUS,		SYSTEM,	BASEBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SYSTEM_TEMP_OAM_0_1_HSC]		= METRIC_EXT_CODE(SYS_BASEBOARD_TEMP,	SYSTEM_TEMP_OAM_0_1_HSC,		CELSIUS,		SYSTEM,	BASEBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SYSTEM_TEMP_OAM_2_3_HSC]		= METRIC_EXT_CODE(SYS_BASEBOARD_TEMP,	SYSTEM_TEMP_OAM_2_3_HSC,		CELSIUS,		SYSTEM,	BASEBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SYSTEM_TEMP_OAM_4_5_HSC]		= METRIC_EXT_CODE(SYS_BASEBOARD_TEMP,	SYSTEM_TEMP_OAM_4_5_HSC,		CELSIUS,		SYSTEM,	BASEBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SYSTEM_TEMP_OAM_6_7_HSC]		= METRIC_EXT_CODE(SYS_BASEBOARD_TEMP,	SYSTEM_TEMP_OAM_6_7_HSC,		CELSIUS,		SYSTEM,	BASEBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SYSTEM_TEMP_UBB_FPGA_0V72_VR]		= METRIC_EXT_CODE(SYS_BASEBOARD_TEMP,	SYSTEM_TEMP_UBB_FPGA_0V72_VR,		CELSIUS,		SYSTEM,	BASEBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SYSTEM_TEMP_UBB_FPGA_3V3_VR]		= METRIC_EXT_CODE(SYS_BASEBOARD_TEMP,	SYSTEM_TEMP_UBB_FPGA_3V3_VR,		CELSIUS,		SYSTEM,	BASEBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SYSTEM_TEMP_RETIMER_0_1_2_3_1V2_VR]	= METRIC_EXT_CODE(SYS_BASEBOARD_TEMP,	SYSTEM_TEMP_RETIMER_0_1_2_3_1V2_VR,	CELSIUS,		SYSTEM,	BASEBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SYSTEM_TEMP_RETIMER_4_5_6_7_1V2_VR]	= METRIC_EXT_CODE(SYS_BASEBOARD_TEMP,	SYSTEM_TEMP_RETIMER_4_5_6_7_1V2_VR,	CELSIUS,		SYSTEM,	BASEBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SYSTEM_TEMP_RETIMER_0_1_0V9_VR]		= METRIC_EXT_CODE(SYS_BASEBOARD_TEMP,	SYSTEM_TEMP_RETIMER_0_1_0V9_VR,		CELSIUS,		SYSTEM,	BASEBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SYSTEM_TEMP_RETIMER_4_5_0V9_VR]		= METRIC_EXT_CODE(SYS_BASEBOARD_TEMP,	SYSTEM_TEMP_RETIMER_4_5_0V9_VR,		CELSIUS,		SYSTEM,	BASEBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SYSTEM_TEMP_RETIMER_2_3_0V9_VR]		= METRIC_EXT_CODE(SYS_BASEBOARD_TEMP,	SYSTEM_TEMP_RETIMER_2_3_0V9_VR,		CELSIUS,		SYSTEM,	BASEBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SYSTEM_TEMP_RETIMER_6_7_0V9_VR]		= METRIC_EXT_CODE(SYS_BASEBOARD_TEMP,	SYSTEM_TEMP_RETIMER_6_7_0V9_VR,		CELSIUS,		SYSTEM,	BASEBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SYSTEM_TEMP_OAM_0_1_2_3_3V3_VR]		= METRIC_EXT_CODE(SYS_BASEBOARD_TEMP,	SYSTEM_TEMP_OAM_0_1_2_3_3V3_VR,		CELSIUS,		SYSTEM,	BASEBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SYSTEM_TEMP_OAM_4_5_6_7_3V3_VR]		= METRIC_EXT_CODE(SYS_BASEBOARD_TEMP,	SYSTEM_TEMP_OAM_4_5_6_7_3V3_VR,		CELSIUS,		SYSTEM,	BASEBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SYSTEM_TEMP_IBC_HSC]			= METRIC_EXT_CODE(SYS_BASEBOARD_TEMP,	SYSTEM_TEMP_IBC_HSC,			CELSIUS,		SYSTEM,	BASEBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SYSTEM_TEMP_IBC]			= METRIC_EXT_CODE(SYS_BASEBOARD_TEMP,	SYSTEM_TEMP_IBC,			CELSIUS,		SYSTEM,	BASEBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_NODE_TEMP_RETIMER]			= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	NODE_TEMP_RETIMER,			CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_NODE_TEMP_IBC_TEMP]			= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	NODE_TEMP_IBC_TEMP,			CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_NODE_TEMP_IBC_2_TEMP]			= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	NODE_TEMP_IBC_2_TEMP,			CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_NODE_TEMP_VDD18_VR_TEMP]		= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	NODE_TEMP_VDD18_VR_TEMP,		CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_NODE_TEMP_04_HBM_B_VR_TEMP]		= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	NODE_TEMP_04_HBM_B_VR_TEMP,		CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_NODE_TEMP_04_HBM_D_VR_TEMP]		= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	NODE_TEMP_04_HBM_D_VR_TEMP,		CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SVI_PLANE_VDDCR_X0_TEMP]		= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	SVI_PLANE_VDDCR_X0_TEMP,		CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SVI_PLANE_VDDCR_X1_TEMP]		= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	SVI_PLANE_VDDCR_X1_TEMP,		CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SVI_PLANE_VDDIO_HBM_B_TEMP]		= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	SVI_PLANE_VDDIO_HBM_B_TEMP,		CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SVI_PLANE_VDDIO_HBM_D_TEMP]		= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	SVI_PLANE_VDDIO_HBM_D_TEMP,		CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SVI_PLANE_VDDIO_04_HBM_B_TEMP]		= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	SVI_PLANE_VDDIO_04_HBM_B_TEMP,		CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SVI_PLANE_VDDIO_04_HBM_D_TEMP]		= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	SVI_PLANE_VDDIO_04_HBM_D_TEMP,		CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SVI_PLANE_VDDCR_HBM_B_TEMP]		= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	SVI_PLANE_VDDCR_HBM_B_TEMP,		CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SVI_PLANE_VDDCR_HBM_D_TEMP]		= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	SVI_PLANE_VDDCR_HBM_D_TEMP,		CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SVI_PLANE_VDDCR_075_HBM_B_TEMP]		= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	SVI_PLANE_VDDCR_075_HBM_B_TEMP,		CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SVI_PLANE_VDDCR_075_HBM_D_TEMP]		= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	SVI_PLANE_VDDCR_075_HBM_D_TEMP,		CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SVI_PLANE_VDDIO_11_GTA_A_TEMP]		= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	SVI_PLANE_VDDIO_11_GTA_A_TEMP,		CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SVI_PLANE_VDDIO_11_GTA_C_TEMP]		= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	SVI_PLANE_VDDIO_11_GTA_C_TEMP,		CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SVI_PLANE_VDDAN_075_GTA_A_TEMP]		= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	SVI_PLANE_VDDAN_075_GTA_A_TEMP,		CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SVI_PLANE_VDDAN_075_GTA_C_TEMP]		= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	SVI_PLANE_VDDAN_075_GTA_C_TEMP,		CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SVI_PLANE_VDDCR_075_UCIE_TEMP]		= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	SVI_PLANE_VDDCR_075_UCIE_TEMP,		CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SVI_PLANE_VDDIO_065_UCIEAA_TEMP]	= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	SVI_PLANE_VDDIO_065_UCIEAA_TEMP,	CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SVI_PLANE_VDDIO_065_UCIEAM_A_TEMP]	= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	SVI_PLANE_VDDIO_065_UCIEAM_A_TEMP,	CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SVI_PLANE_VDDIO_065_UCIEAM_C_TEMP]	= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	SVI_PLANE_VDDIO_065_UCIEAM_C_TEMP,	CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SVI_PLANE_VDDCR_SOCIO_A_TEMP]		= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	SVI_PLANE_VDDCR_SOCIO_A_TEMP,		CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SVI_PLANE_VDDCR_SOCIO_C_TEMP]		= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	SVI_PLANE_VDDCR_SOCIO_C_TEMP,		CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SVI_PLANE_VDDAN_075_TEMP]		= METRIC_EXT_CODE(SYS_GPUBOARD_TEMP,	SVI_PLANE_VDDAN_075_TEMP,		CELSIUS,		SYSTEM,	GPUBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SYSTEM_POWER_UBB_POWER]			= METRIC_EXT_CODE(SYS_BASEBOARD_POWER,	SYSTEM_POWER_UBB_POWER,			WATT,			SYSTEM,	BASEBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
	[SMU_15_SYSTEM_POWER_UBB_POWER_THRESHOLD]	= METRIC_EXT_CODE(SYS_BASEBOARD_POWER,	SYSTEM_POWER_UBB_POWER_THRESHOLD,	WATT,			SYSTEM,	BASEBOARD,	METRIC_EXT_FLAG(DATA_FILTER_INST)),
};

struct drv_metrics {
	uint32_t num_metric;
	struct amdgv_gpumon_metric_ext metric[MAX_NUM_METRICS];
	struct {
		void *addr;
		enum metric_addr_encoding encoding;
	} runtime_config[MAX_NUM_METRICS];
};

enum smu_table_type {
	SMU_TABLE__METRICS,
	SMU_TABLE__STATIC_METRICS,
	SMU_TABLE__SYSTEM_METRICS,
	SMU_TABLE__NUM,
};

struct smu_table {
	uint64_t timestamp;
	void *table;
	uint32_t size;
	uint32_t msg;
};

struct smu_v15_0_8_table_context {
	/* Defined by driver, by used by usermode tools.*/
	struct smu_local_memory tool_xchg_mem;

	struct smu_local_memory driver_xchg_mem;
	struct smu_table tables[SMU_TABLE__NUM];
};
#define ADAPT_TO_SMU(adapt)		((struct smu_context *)((adapt)->pp.smu_backend))
#define SMU_TO_TABLE_CONTEXT(smu)	((struct smu_v15_0_8_table_context *)smu->smu_table_context)
#define ADAPT_TO_SMU_TABLE(adapt, type) (SMU_TO_TABLE_CONTEXT(ADAPT_TO_SMU(adapt))->tables[type].table)

#endif