/*
 * Copyright Advanced Micro Devices, Inc.
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef __SMI_NIC_STATS_H__
#define __SMI_NIC_STATS_H__

#include <string>
#include <unordered_set>

namespace smi_nic_stats {

inline const std::unordered_set<std::string> pensando_vendor_stats = {
	"frames_rx_ok",
	"frames_rx_all",
	"frames_rx_bad_fcs",
	"frames_rx_bad_all",
	"octets_rx_ok",
	"octets_rx_all",
	"frames_rx_unicast",
	"frames_rx_multicast",
	"frames_rx_broadcast",
	"frames_rx_pause",
	"frames_rx_bad_length",
	"frames_rx_undersized",
	"frames_rx_oversized",
	"frames_rx_fragments",
	"frames_rx_jabber",
	"frames_rx_pripause",
	"frames_rx_stomped_crc",
	"frames_rx_too_long",
	"frames_rx_vlan_good",
	"frames_rx_dropped",
	"frames_rx_less_than_64b",
	"frames_rx_64b",
	"frames_rx_65b_127b",
	"frames_rx_128b_255b",
	"frames_rx_256b_511b",
	"frames_rx_512b_1023b",
	"frames_rx_1024b_1518b",
	"frames_rx_1519b_2047b",
	"frames_rx_2048b_4095b",
	"frames_rx_4096b_8191b",
	"frames_rx_8192b_9215b",
	"frames_rx_other",
	"frames_tx_ok",
	"frames_tx_all",
	"frames_tx_bad",
	"octets_tx_ok",
	"octets_tx_total",
	"frames_tx_unicast",
	"frames_tx_multicast",
	"frames_tx_broadcast",
	"frames_tx_pause",
	"frames_tx_pripause",
	"frames_tx_vlan",
	"frames_tx_less_than_64b",
	"frames_tx_64b",
	"frames_tx_65b_127b",
	"frames_tx_128b_255b",
	"frames_tx_256b_511b",
	"frames_tx_512b_1023b",
	"frames_tx_1024b_1518b",
	"frames_tx_1519b_2047b",
	"frames_tx_2048b_4095b",
	"frames_tx_4096b_8191b",
	"frames_tx_8192b_9215b",
	"frames_tx_other",
	"frames_tx_truncated",
	"frames_tx_pri_0",
	"frames_tx_pri_1",
	"frames_tx_pri_2",
	"frames_tx_pri_3",
	"frames_tx_pri_4",
	"frames_tx_pri_5",
	"frames_tx_pri_6",
	"frames_tx_pri_7",
	"frames_rx_pri_0",
	"frames_rx_pri_1",
	"frames_rx_pri_2",
	"frames_rx_pri_3",
	"frames_rx_pri_4",
	"frames_rx_pri_5",
	"frames_rx_pri_6",
	"frames_rx_pri_7",
	"tx_pripause_0_1us_count",
	"tx_pripause_1_1us_count",
	"tx_pripause_2_1us_count",
	"tx_pripause_3_1us_count",
	"tx_pripause_4_1us_count",
	"tx_pripause_5_1us_count",
	"tx_pripause_6_1us_count",
	"tx_pripause_7_1us_count",
	"rx_pripause_0_1us_count",
	"rx_pripause_1_1us_count",
	"rx_pripause_2_1us_count",
	"rx_pripause_3_1us_count",
	"rx_pripause_4_1us_count",
	"rx_pripause_5_1us_count",
	"rx_pripause_6_1us_count",
	"rx_pripause_7_1us_count",
	"rx_pause_1us_count",

	"corrected_blocks",
	"uncorrectable_blocks",
	"corrected_bits",
	"fec_symbols_err_0",
	"fec_symbols_err_1",
	"fec_symbols_err_2",
	"fec_symbols_err_3",
	"fec_symbols_err_4",
	"fec_symbols_err_5",
	"fec_symbols_err_6",
	"fec_symbols_err_7",
	"fec_symbols_err_8",
	"fec_symbols_err_9",
	"fec_symbols_err_10",
	"fec_symbols_err_11",
	"fec_symbols_err_12",
	"fec_symbols_err_13",
	"fec_symbols_err_14",
	"fec_symbols_err_15",
};

inline const std::unordered_set<std::string> broadcom_vendor_stats = {
	"rx_total_ring_discards",
	"tx_total_ring_discards",

	"pfc_pri0_tx_transitions",
	"pfc_pri1_tx_transitions",
	"pfc_pri2_tx_transitions",
	"pfc_pri3_tx_transitions",
	"pfc_pri4_tx_transitions",
	"pfc_pri5_tx_transitions",
	"pfc_pri6_tx_transitions",
	"pfc_pri7_tx_transitions",
	"pfc_pri0_rx_transitions",
	"pfc_pri1_rx_transitions",
	"pfc_pri2_rx_transitions",
	"pfc_pri3_rx_transitions",
	"pfc_pri4_rx_transitions",
	"pfc_pri5_rx_transitions",
	"pfc_pri6_rx_transitions",
	"pfc_pri7_rx_transitions",

	"tx_pfc_ena_frames_pri0",
	"tx_pfc_ena_frames_pri1",
	"tx_pfc_ena_frames_pri2",
	"tx_pfc_ena_frames_pri3",
	"tx_pfc_ena_frames_pri4",
	"tx_pfc_ena_frames_pri5",
	"tx_pfc_ena_frames_pri6",
	"tx_pfc_ena_frames_pri7",

	"rx_pfc_frames",
	"tx_pfc_frames",

	"rx_bytes_cos0",
	"rx_bytes_cos1",
	"rx_bytes_cos2",
	"rx_bytes_cos3",
	"rx_bytes_cos4",
	"rx_bytes_cos5",
	"rx_bytes_cos6",
	"rx_bytes_cos7",
	"tx_bytes_cos0",
	"tx_bytes_cos1",
	"tx_bytes_cos2",
	"tx_bytes_cos3",
	"tx_bytes_cos4",
	"tx_bytes_cos5",
	"tx_bytes_cos6",
	"tx_bytes_cos7",

	"continuous_roce_pause_events",

	"pfc_wd_storms_detected_p0",
	"pfc_wd_storms_detected_p1",
	"pfc_wd_storms_detected_p2",
	"pfc_wd_storms_detected_p3",
	"pfc_wd_storms_detected_p4",
	"pfc_wd_storms_detected_p5",
	"pfc_wd_storms_detected_p6",
	"pfc_wd_storms_detected_p7",

	"rx_fec_uncorrectable_blocks",
	"rx_fec_corrected_blocks",
};

} // namespace smi_nic_stats

#endif // __SMI_NIC_STATS_H__
