/* Copyright Advanced Micro Devices, Inc.
 *
 * SPDX-License-Identifier: MIT
 */

#include "amdgv_device.h"
#include "amdgv_log.h"
#include "amdgv_log_internal.h"

#define error_category(comp)                                                                  \
	static const struct log_text                                                          \
		AMDGV_LOG_##comp##_LIST[AMDGV_LOG_SUBCODE(AMDGV_LOG_##comp##_MAX + 1)]

#define add_entry(subcode, arg, level, txt)                                                         \
	{                                                                                               \
		subcode, #subcode, arg, level, AMDGV_LOG_PRINT_HEADER txt "\n", 0                                   \
	}

#define add_entry_ext(subcode, arg, level, txt)                                                     \
	{                                                                                     	        \
		subcode, #subcode, arg, level, AMDGV_LOG_PRINT_HEADER txt "\n", AMDGV_LOG_FLAG_EXT 	    \
	}

#define add_category(comp)                                                                    \
	{                                                                                     \
		AMDGV_LOG_CATEGORY_##comp, AMDGV_LOG_##comp##_LIST,                       \
			AMDGV_LOG_SUBCODE(AMDGV_LOG_##comp##_MAX + 1)                     \
	}

#define category_not_used()                                                                   \
	{                                                                                     \
		AMDGV_LOG_CATEGORY_NON_USED, 0, 0                                           \
	}

/*
 * Error subcode entry and description
 *
 * Format:
 * error_category(component) = {
 *     add_entry(subcode, arg_type, description),
 * };
 *
 */
error_category(DRIVER) = {
	add_entry(AMDGV_LOG_DRIVER_SPIN_LOCK_BUSY, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED,
		  "Spin lock is busy, didn't free after timeout. Still waiting!"),
	add_entry(AMDGV_LOG_DRIVER_ALLOC_SYSTEM_MEM_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Allocate system memory failed (length: %llu)!"),
	add_entry(AMDGV_LOG_DRIVER_RESERVE_SYSTEM_MEM_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Reserve system memory failed (length: %llu)!"),
	add_entry(AMDGV_LOG_DRIVER_CREATE_GFX_WORKQUEUE_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Create GFX workqueue failed."),
	add_entry(AMDGV_LOG_DRIVER_CREATE_MM_WORKQUEUE_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Create MM workqueue failed."),
	add_entry(AMDGV_LOG_DRIVER_BUFFER_OVERFLOW, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_MED,
		  "Buffer overflowed (number of entry dropped: %llu)."),

	add_entry(AMDGV_LOG_DRIVER_DEV_INIT_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "Failed to init dev(0x%llx)."),
	add_entry(AMDGV_LOG_DRIVER_CREATE_THREAD_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Cannot create thread."),
	add_entry(AMDGV_LOG_DRIVER_NO_ACCESS_PCI_REGION, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "Cannot access PCI region."),
	add_entry(AMDGV_LOG_DRIVER_MMIO_FAIL, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "Cannot map MMIO BAR."),
	add_entry(AMDGV_LOG_DRIVER_INTERRUPT_INIT_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "Failed to enable interrupt vector(%llu)."),

	add_entry(AMDGV_LOG_DRIVER_INVALID_VALUE, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Invalid value(%lld)."),
	add_entry(AMDGV_LOG_DRIVER_CREATE_MUTEX_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Cannot create mutex."),
	add_entry(AMDGV_LOG_DRIVER_CREATE_TIMER_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Cannot create timer."),
	add_entry(AMDGV_LOG_DRIVER_CREATE_EVENT_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Cannot create synchronization event."),
	add_entry(AMDGV_LOG_DRIVER_CREATE_SPIN_LOCK_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Cannot create spin lock."),

	add_entry(AMDGV_LOG_DRIVER_ALLOC_FB_MEM_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Allocate FB memory failed (length: %llu)!"),
	add_entry(AMDGV_LOG_DRIVER_ALLOC_DMA_MEM_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Allocate DMA memory failed (length: %llu)!"),
	add_entry(AMDGV_LOG_DRIVER_MAP_DMA_MEM_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Map DMA memory to gart failed (length: %llu)!"),
	add_entry(AMDGV_LOG_DRIVER_NO_FB_MANAGER, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "FB memory manager is not allocated."),
	add_entry(AMDGV_LOG_DRIVER_HW_INIT_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "Failed to HW init."),
	add_entry(AMDGV_LOG_DRIVER_SW_INIT_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to SW init."),

	add_entry(AMDGV_LOG_DRIVER_INIT_CONFIG_ERROR, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to parse init config."),
	add_entry(AMDGV_LOG_DRIVER_ERROR_LOGGING_FAILED, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to start error logging."),
	add_entry(AMDGV_LOG_DRIVER_CREATE_RWLOCK_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Cannot create read/write spinlock."),
	add_entry(AMDGV_LOG_DRIVER_CREATE_RWSEMA_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Cannot create read/write semaphore."),
	add_entry(AMDGV_LOG_DRIVER_GET_READ_LOCK_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to acquire read spinlock."),

	add_entry(AMDGV_LOG_DRIVER_GET_WRITE_LOCK_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to acquire write spinlock."),
	add_entry(AMDGV_LOG_DRIVER_GET_READ_SEMA_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to acquire read semaphore."),
	add_entry(AMDGV_LOG_DRIVER_GET_WRITE_SEMA_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to acquire write semaphore."),

	add_entry(AMDGV_LOG_DRIVER_DIAG_DATA_INIT_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to initialize diagnosis data."),
	add_entry(AMDGV_LOG_DRIVER_DIAG_DATA_MEM_REQ_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to request memory for diagnosis data (length: %llu)."),
	add_entry(AMDGV_LOG_DRIVER_DIAG_DATA_VADDR_REQ_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to get the vaddr for memory block."),
	add_entry(AMDGV_LOG_DRIVER_DIAG_DATA_BUS_ADDR_REQ_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to get the bus addr for memory block"),

	add_entry(AMDGV_LOG_DRIVER_HRTIMER_START_FAIL, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to start kernel hrtimer"),
	add_entry(AMDGV_LOG_DRIVER_CREATE_DRIVER_FILE_FAIL, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to create driver file"),
	add_entry(AMDGV_LOG_DRIVER_CREATE_DEVICE_FILE_FAIL, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to create device file"),
	add_entry(AMDGV_LOG_DRIVER_CREATE_DEBUGFS_FILE_FAIL, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to create debugfs file"),
	add_entry(AMDGV_LOG_DRIVER_CREATE_DEBUGFS_DIR_FAIL, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to create debugfs dir"),

	add_entry(AMDGV_LOG_DRIVER_PCI_ENABLE_DEVICE_FAIL, LOG_DATA_ARG_64,
		AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to enable pci device (0x%llx)"),
	add_entry(AMDGV_LOG_DRIVER_FB_MAP_FAIL, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_ERROR_HIGH, "Failed to map FB"),
	add_entry(AMDGV_LOG_DRIVER_DOORBELL_MAP_FAIL, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_ERROR_HIGH, "Failed to map DOORBELL"),
	add_entry(AMDGV_LOG_DRIVER_PCI_REGISTER_DRIVER_FAIL, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_ERROR_HIGH, "Failed to register pci driver."),
	add_entry(AMDGV_LOG_DRIVER_VF_RESIZE_BAR_FAIL, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_ERROR_HIGH, "Failed to resize VF BAR."),

	add_entry(AMDGV_LOG_DRIVER_ALLOC_IOVA_ALIGN_FAIL, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_WARNING, "Allocate iova method memory failed."),
	add_entry(AMDGV_LOG_DRIVER_SET_MEM_ATTRIBUTE_FAIL, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to set memory attribute."),
	add_entry(AMDGV_LOG_DRIVER_FIND_ADDR_PTE_FAIL, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to find address PTE."),
	add_entry(AMDGV_LOG_DRIVER_ALLOC_SG_FAIL, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to allocate scatter-gather list."),

	add_entry(AMDGV_LOG_DRIVER_ROM_MAP_FAIL, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "Cannot map ROM BAR."),

	add_entry_ext(AMDGV_LOG_DRIVER_FULL_ACCESS_TIMEOUT, LOG_DATA_ARG_THREE_64_EXT,
		AMDGV_LOG_SEVERITY_ERROR_LOW, "VF %llu full access timeout. |start time: %llu| - |end time: %llu|"),

	add_entry(AMDGV_LOG_DRIVER_MIGRATION_INIT_FAIL, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to init migration."),
	add_entry(AMDGV_LOG_DRIVER_MIGRATION_GET_MIG_INFO_FAIL, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to get migration info."),
	add_entry(AMDGV_LOG_DRIVER_MIGRATION_THREAD_INIT_FAIL, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to create copy data thread."),
	add_entry(AMDGV_LOG_DRIVER_MIGRATION_SETUP_ENV_FAIL, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to setup migration environment."),
	add_entry(AMDGV_LOG_DRIVER_MIGRATION_DATA_COPY_FAIL, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to copy migration data."),
	add_entry(AMDGV_LOG_DRIVER_MIGRATION_IMPORT_FAIL, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to import migration data."),
	add_entry(AMDGV_LOG_DRIVER_MIGRATION_EXPORT_FAIL, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to export migration data."),
	add_entry(AMDGV_LOG_DRIVER_PCIE_CAP_MISSING, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Device does not support PCIe capability 0x%llx."),
	add_entry(AMDGV_LOG_DRIVER_REGISTER_INTERRUPT_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to register interrupt handler."),
	add_entry_ext(AMDGV_LOG_DRIVER_HBM_MGMT_INIT_FAIL, LOG_DATA_ARG_THREE_64_EXT,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to create HBM mgmt interface for FB at 0x%llx size=0x%llx."),
	add_entry(AMDGV_LOG_DRIVER_PF_FB_SIZE, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_INFO, "PF FB size set to %llu MB."),
	add_entry(AMDGV_LOG_DRIVER_FB_APERTURE_SIZE, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_INFO, "FB aperture size 0x%llx bytes."),
	add_entry(AMDGV_LOG_DRIVER_FB_BLOCK_SIZE_ZERO, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Attempt to create FB block with size 0."),
	add_entry(AMDGV_LOG_DRIVER_NO_FREE_FB_BLOCK, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "No free FB block slot available."),
	add_entry(AMDGV_LOG_DRIVER_PF_FB_RECONFIG_DENIED, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Cannot reconfigure PF FB."),
	add_entry(AMDGV_LOG_DRIVER_FB_SIZE_UNALIGNED, LOG_DATA_ARG_32_32,
		  AMDGV_LOG_SEVERITY_WARNING, "FB size not aligned to %u MB; rounded down to %u MB."),
	add_entry(AMDGV_LOG_DRIVER_ASYMMETRIC_FB_NOT_SUPPORTED, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Asymmetric FB is not supported on current ASIC."),
	add_entry(AMDGV_LOG_DRIVER_ACTIVE_VF_FB_CHANGE_DENIED, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Cannot change FB size of an active VF."),
	add_entry(AMDGV_LOG_DRIVER_VF_FB_RECONFIG_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_WARNING, "Failed to reconfigure VF FB during defragment."),
	add_entry_ext(AMDGV_LOG_DRIVER_FFBM_VF_FB_TMR_LAYOUT, LOG_DATA_ARG_THREE_64_EXT,
		  AMDGV_LOG_SEVERITY_DEBUG, "FFBM FB TMR offset %llu MB, size %llu MB, tmr size %llu MB."),
	add_entry(AMDGV_LOG_DRIVER_IPD_FB_SIZE_MISMATCH, LOG_DATA_ARG_32_32,
		  AMDGV_LOG_SEVERITY_WARNING, "Possibly wrong IP discovery data: total usable FB %u MB > numa FB %u MB."),
	add_entry(AMDGV_LOG_DRIVER_TOTAL_VF_FB_SIZE, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_INFO, "Total VF FB size %llu MB."),
	add_entry(AMDGV_LOG_DRIVER_VF_FB_LAYOUT, LOG_DATA_ARG_32_32,
		  AMDGV_LOG_SEVERITY_INFO, "VF FB starts at %u MB, size %u MB."),
	add_entry(AMDGV_LOG_DRIVER_ACTIVE_VF_DETECTED, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_WARNING, "Active VF detected; skipping removal."),
	add_entry(AMDGV_LOG_DRIVER_SERVICE_VM_ENABLED, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_INFO, "Service VM enabled."),
	add_entry(AMDGV_LOG_DRIVER_VF_MGMT_MODE, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_INFO, "VF management mode change (enter=%llu)."),
	add_entry(AMDGV_LOG_DRIVER_ENABLED_VF_NUM, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_INFO, "Enabled VF number set to %llu."),
	add_entry(AMDGV_LOG_DRIVER_LIVE_UPDATE_SLOT_OVERFLOW, LOG_DATA_ARG_32_32,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Live-update slot overflow: slot %u exceeds %u available slots."),
	add_entry_ext(AMDGV_LOG_DRIVER_PCI_CFG_WAIT_TIMEOUT, LOG_DATA_ARG_FIVE_64_EXT,
		  AMDGV_LOG_SEVERITY_WARNING,
		  "Timeout waiting for PCI config [0x%llx]. check_ne=%llu expect=0x%llx actual=0x%llx elapsed=%llu us."),
	add_entry(AMDGV_LOG_DRIVER_IRQ_HANDLER_TIMEOUT, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Timeout waiting for IRQ handler (elapsed %llu us)."),

	/* this one is the MAX - test entry intentionally on ERROR ring */
	add_entry(AMDGV_LOG_DRIVER_MAX, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "This is error log collect test for DRIVER component (test count %llu)."),
};

error_category(FW) = {
	add_entry(AMDGV_LOG_FW_CMD_ALLOC_BUF_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "PSP command alloc buffer failed!"),
	add_entry(AMDGV_LOG_FW_CMD_BUF_PREP_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "PSP command buffer prepare failed!"),
	add_entry(AMDGV_LOG_FW_RING_INIT_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to initialize PSP ring."),
	add_entry(AMDGV_LOG_FW_UCODE_APPLY_SECURITY_POLICY_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to apply PSP security policy."),
	add_entry(AMDGV_LOG_FW_START_RING_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to start PSP ring."),

	add_entry(AMDGV_LOG_FW_UCODE_LOAD_FAIL, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "Failed to load FW %llu"),
	add_entry(AMDGV_LOG_FW_EXIT_FAIL, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "Failed to cleanup PSP."),
	add_entry(AMDGV_LOG_FW_INIT_FAIL, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "Failed to init PSP."),
	add_entry(AMDGV_LOG_FW_CMD_SUBMIT_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "PSP command submit failed."),
	add_entry(AMDGV_LOG_FW_CMD_FENCE_WAIT_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "PSP command fence wait failed."),

	add_entry(AMDGV_LOG_FW_TMR_LOAD_FAIL, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "Failed to load TMR."),
	add_entry(AMDGV_LOG_FW_TOC_LOAD_FAIL, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "Failed to load TOC."),
	add_entry(AMDGV_LOG_FW_RAS_LOAD_FAIL, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "Failed to load RAS."),
	add_entry(AMDGV_LOG_FW_RAS_UNLOAD_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to unload RAS."),
	add_entry(AMDGV_LOG_FW_RAS_TA_INVOKE_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Failed to invoke RAS TA."),
	add_entry(AMDGV_LOG_FW_RAS_TA_ERR_INJECT_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Failed to error inject in RAS TA."),
	add_entry(AMDGV_LOG_FW_RAS_TA_ENABLE_RAS_FEATURE_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Failed to enable ras feature in RAS TA."),

	add_entry(AMDGV_LOG_FW_ASD_LOAD_FAIL, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "Failed to load ASD."),
	add_entry(AMDGV_LOG_FW_ASD_UNLOAD_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to unload ASD."),
	add_entry(AMDGV_LOG_FW_AUTOLOAD_FAIL, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "Failed to start autoload."),
	add_entry(AMDGV_LOG_FW_VFGATE_FAIL, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "Failed to execute VF gate command."),
	add_entry(AMDGV_LOG_FW_XGMI_LOAD_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to load XGMI."),

	add_entry(AMDGV_LOG_FW_XGMI_UNLOAD_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to unload XGMI."),
	add_entry(AMDGV_LOG_FW_XGMI_TA_INVOKE_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to invoke XGMI TA."),

	add_entry(AMDGV_LOG_FW_TMR_INIT_FAIL, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "Failed to init TMR."),
	add_entry(AMDGV_LOG_FW_NOT_SUPPORTED_FEATURE, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "The feature is not supported."),
	add_entry(AMDGV_LOG_FW_GET_PSP_TRACELOG_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Failed to Get PSP Trace Log, status=0x%llx."),

	add_entry(AMDGV_LOG_FW_SET_SNAPSHOT_ADDR_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Failed to set Snapshot address, status=0x%llx."),
	add_entry(AMDGV_LOG_FW_SNAPSHOT_TRIGGER_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Failed to trigger Snapshot, status=0x%llx."),

	add_entry(AMDGV_LOG_FW_MIGRATION_GET_PSP_INFO_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Failed to get migration version, status=0x%llx."),
	add_entry(AMDGV_LOG_FW_MIGRATION_EXPORT_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Failed migration export, status=0x%llx."),
	add_entry(AMDGV_LOG_FW_MIGRATION_IMPORT_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Failed migration import, status=0x%llx."),
	add_entry(AMDGV_LOG_FW_BL_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "Timeout waiting for PSP Bootloader to finish GPU boot process"),

	add_entry(AMDGV_LOG_FW_RAS_BOOT_FAIL, LOG_DATA_ARG_16_16_32,
			AMDGV_LOG_SEVERITY_ERROR_HIGH, "Firmware boot failed, socket: %u, aid: %u, fw status is 0x%x"),

	add_entry(AMDGV_LOG_FW_MAILBOX_ERROR, LOG_DATA_ARG_16_16_32,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "VF %u PSP mailbox failure. status: %u amdgv_fw_id: %u."),

	add_entry(AMDGV_LOG_FW_RAS_MEM_TRAIN_FAIL, LOG_DATA_ARG_16_16_32,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "socket: %u, aid: %u, hbm: %d, memory training failed."),

	add_entry(AMDGV_LOG_FW_RAS_FW_LOAD_FAIL, LOG_DATA_ARG_32_32,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "socket: %d, aid: %d, firmware load failed at boot time"),

	add_entry(AMDGV_LOG_FW_RAS_WAFL_LINK_TRAIN_FAIL, LOG_DATA_ARG_32_32,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "socket: %d, aid: %d, wafl link training failed"),

	add_entry(AMDGV_LOG_FW_RAS_XGMI_LINK_TRAIN_FAIL, LOG_DATA_ARG_32_32,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "socket: %d, aid: %d, xgmi link training failed"),

	add_entry(AMDGV_LOG_FW_RAS_USR_CP_LINK_TRAIN_FAIL, LOG_DATA_ARG_32_32,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "socket: %d, aid: %d, usr cp link training failed"),

	add_entry(AMDGV_LOG_FW_RAS_USR_DP_LINK_TRAIN_FAIL, LOG_DATA_ARG_32_32,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "socket: %d, aid: %d, usr dp link training failed"),

	add_entry(AMDGV_LOG_FW_RAS_HBM_MEM_TEST_FAIL, LOG_DATA_ARG_16_16_32,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "socket: %u, aid: %u, hbm: %d, hbm memory test failed."),

	add_entry(AMDGV_LOG_FW_RAS_HBM_BIST_TEST_FAIL, LOG_DATA_ARG_16_16_32,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "socket: %u, aid: %u, hbm: %d, hbm bist test failed."),

	add_entry(AMDGV_LOG_FW_RAS_BOOT_REG_READ_FAIL, LOG_DATA_ARG_32_32,
			AMDGV_LOG_SEVERITY_ERROR_HIGH, "Firmware boot failed, MP0_SMN_C2PMSG_126 read fail, boot error: 0x%x, fw status: 0x%x"),

	add_entry(AMDGV_LOG_FW_MIGRATION_VF_CP_NOT_SUPPORTED, LOG_DATA_ARG_64,
			AMDGV_LOG_SEVERITY_ERROR_LOW, "VF %llu CP firmware doesn't support migration"),

	add_entry(AMDGV_LOG_FW_MIGRATION_GET_DATA_SIZE_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Failed to get migration data size, status=0x%llx."),
	add_entry(AMDGV_LOG_FW_MIGRATION_DATA_OVERSIZE, LOG_DATA_ARG_32_32,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "PSP migration data size %u exceeds allocated %u."),
	add_entry(AMDGV_LOG_FW_MIGRATION_AUTOLOAD_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Failed migration autoload, status=0x%llx."),
	add_entry(AMDGV_LOG_FW_SMU_NOT_RESPONDING, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "SMU firmware is not responding; requested operation aborted."),
	add_entry(AMDGV_LOG_FW_TRIGGER_VF_FLR_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to send trigger VF FLR message to SMU."),
	add_entry(AMDGV_LOG_FW_TRIGGER_VF_FLR_NOT_IMPLEMENTED, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Trigger VF FLR SMU callback not implemented."),

	add_entry_ext(AMDGV_LOG_FW_PSP_RING_RESP_TIMEOUT, LOG_DATA_ARG_THREE_64_EXT,
		  AMDGV_LOG_SEVERITY_WARNING,
		  "Timeout waiting for PSP ring response [0x%llx] (elapsed %llu us)."),
	add_entry(AMDGV_LOG_FW_PSP_MB_INT_TIMEOUT, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Timeout waiting for PSP mailbox interrupt (elapsed %llu us)."),
	add_entry(AMDGV_LOG_FW_PSP_TOS_LOADED_TIMEOUT, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "Timeout waiting for PSP TOS loaded status (elapsed %llu us)."),
	add_entry(AMDGV_LOG_FW_PSP_BOOT_COMPLETE_TIMEOUT, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "Timeout waiting for PSP boot complete (elapsed %llu us)."),
	add_entry(AMDGV_LOG_FW_RLC_AUTOLOAD_TIMEOUT, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Timeout waiting for RLC autoload complete (elapsed %llu us)."),
	add_entry(AMDGV_LOG_FW_LSDMA_PIO_TIMEOUT, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Timeout waiting for LSDMA PIO (elapsed %llu us)."),
	add_entry(AMDGV_LOG_FW_CP_DMA_PIO_TIMEOUT, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Timeout waiting for CP DMA PIO (elapsed %llu us)."),

	/* this one is the MAX */
	add_entry(AMDGV_LOG_FW_MAX, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_INFO,
		  "This is error log collect test for FW component (test count %llu)."),
};

error_category(RESET) = {
	add_entry(AMDGV_LOG_RESET_GPU, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_LOW,
		  "Issuing Whole GPU reset."),
	add_entry(AMDGV_LOG_RESET_GPU_FAILED, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_HIGH,
		  "Whole GPU reset failed!"),
	add_entry(AMDGV_LOG_RESET_FLR, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_LOW,
		  "Issuing FLR on vf: %u."),
	add_entry(AMDGV_LOG_RESET_FLR_FAILED, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "FLR failed on vf : %u!"),
	add_entry(AMDGV_LOG_RESET_GPU_HIVE_FAILED, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_HIGH,
			"Unable to perform Whole GPU reset because one or more connected devices are in RMA state."),
	add_entry(AMDGV_LOG_RESET_PF_SOFT_FLR_DONE, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_INFO,
		  "PF soft FLR completed successfully."),
	add_entry(AMDGV_LOG_RESET_NOTIFY_VF, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_DEBUG,
		  "Notifying reset to function."),
	add_entry(AMDGV_LOG_RESET_NOTIFY_VF_COMPLETION, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_DEBUG,
		  "Notifying whole GPU reset completion to function."),
	add_entry(AMDGV_LOG_RESET_PROGRAM_VF_MC_SETTINGS, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_DEBUG,
		  "Programming guest MC settings."),
	add_entry(AMDGV_LOG_RESET_FLR_SET_ACC_BITS_DIRTY, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_DEBUG,
		  "Set VF acc bits to all-dirty before VF FLR (no PF SDMA ring)."),
	add_entry(AMDGV_LOG_RESET_FLR_DISABLED, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_INFO,
		  "VF FLR is disabled."),
	add_entry(AMDGV_LOG_RESET_FLR_DONE, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_DEBUG,
		  "FLR completed."),
	add_entry(AMDGV_LOG_RESET_DROP_ORPHAN_REQUEST, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_DEBUG,
		  "Dropping orphan chain reset request."),
	add_entry(AMDGV_LOG_RESET_FLR_START, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_DEBUG,
		  "Starting FLR."),
	add_entry(AMDGV_LOG_RESET_FLR_RLC_IDLE_FAIL, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "Failed to idle RLC state after FLR."),
	add_entry(AMDGV_LOG_RESET_FLR_TRANS_PENDING, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_WARNING,
		  "Pending transaction not drained before FLR; aborting data transaction."),
	add_entry(AMDGV_LOG_RESET_FLR_GRBM_DIRTY, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_WARNING,
		  "GRBM_STATUS2 is not clean before FLR."),
	add_entry(AMDGV_LOG_RESET_FLR_GRBM_NOT_CLEAN, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "GRBM_STATUS2 is not clean after FLR."),
	add_entry(AMDGV_LOG_RESET_PF_FLR_NOT_SUPPORTED, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_LOW,
		  "PF FLR is not supported."),
	add_entry(AMDGV_LOG_RESET_PF_FLR_SHARED_XCC_MASK, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_WARNING,
		  "PF FLR not allowed due to shared xcc mask."),
	add_entry(AMDGV_LOG_RESET_GPU_DONE, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_INFO,
		  "Whole GPU reset completed"),

	add_entry(AMDGV_LOG_RESET_GPU_CONFIG_CHANGE, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_INFO,
		  "Issuing Whole GPU reset to update GPU configuration."),
	add_entry(AMDGV_LOG_RESET_GPU_UNLOAD, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_INFO,
		  "Issuing Whole GPU reset for driver unload."),
	add_entry(AMDGV_LOG_RESET_GPU_RELOAD, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_INFO,
		  "Issuing Whole GPU reset for driver reload."),

	/* this one is the MAX */
	add_entry(AMDGV_LOG_RESET_MAX, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_INFO,
		  "This is error log collect test for RESET component (test count %llu)."),
};

error_category(IOV) = {
	add_entry(AMDGV_LOG_IOV_NO_GPU_IOV_CAP, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "No GPU_IOV caps found."),
	add_entry(AMDGV_LOG_IOV_ASIC_NO_SRIOV_SUPPORT, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "ASIC has no SRIOV support."),
	add_entry(AMDGV_LOG_IOV_ENABLE_SRIOV_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "Failed to properly enable SRIOV."),
	add_entry(AMDGV_LOG_IOV_CMD_TIMEOUT, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "Timeout of waiting command complete (%llu us)."),
	add_entry(AMDGV_LOG_IOV_CMD_ERROR, LOG_DATA_ARG_32_32, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "Command Error (cmd: 0x%X, status: 0x%X)."),

	add_entry(AMDGV_LOG_IOV_INIT_IV_RING_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Init IV ring failed."),
	add_entry(AMDGV_LOG_IOV_SRIOV_STRIDE_ERROR, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "Only SRIOV stride = 1 is supported."),
	add_entry(AMDGV_LOG_IOV_WS_SAVE_TIMEOUT, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "SRIOV SAVE failed!"),
	add_entry(AMDGV_LOG_IOV_WS_IDLE_TIMEOUT, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "SRIOV IDLE failed!"),
	add_entry(AMDGV_LOG_IOV_WS_RUN_TIMEOUT, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "SRIOV RUN failed!"),
	add_entry(AMDGV_LOG_IOV_WS_LOAD_TIMEOUT, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "SRIOV LOAD failed!"),
	add_entry(AMDGV_LOG_IOV_WS_SHUTDOWN_TIMEOUT, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "SRIOV SHUTDOWN failed!"),
	add_entry(AMDGV_LOG_IOV_WS_ALREADY_SHUTDOWN, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED,
		  "VF is already in SHUTDOWN state, cannot shutdown again."),
	add_entry(AMDGV_LOG_IOV_WS_INFINITE_LOOP, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW,
		  "Potential Infinite loop detected in WS State Machine."),
	add_entry(AMDGV_LOG_IOV_WS_REENTRANT_ERROR, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW,
		  "WS State Machine being called from different threads at the same time."),
	add_entry(AMDGV_LOG_IOV_LIVE_MIGRATION_EXPORT_STATIC, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_INFO,
		"Live migration: Exporting static data."),
	add_entry(AMDGV_LOG_IOV_LIVE_MIGRATION_EXPORT_DYNAMIC, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_INFO,
		"Live migration: Exporting dynamic data."),
	add_entry(AMDGV_LOG_IOV_LIVE_MIGRATION_IMPORT_PREPARE, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_INFO,
		"Live migration: Preparing import."),
	add_entry(AMDGV_LOG_IOV_LIVE_MIGRATION_IMPORT_STATIC, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_INFO,
		"Live migration: Importing static data."),
	add_entry(AMDGV_LOG_IOV_LIVE_MIGRATION_IMPORT_DYNAMIC, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_INFO,
		"Live migration: Importing dynamic data."),
	add_entry(AMDGV_LOG_IOV_LIVE_MIGRATION_EXPORT_STATIC_FAILED, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_ERROR_HIGH,
		"Live migration failed: Export static data error."),
	add_entry(AMDGV_LOG_IOV_LIVE_MIGRATION_EXPORT_DYNAMIC_FAILED, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_ERROR_HIGH,
		"Live migration failed: Export dynamic data error."),
	add_entry(AMDGV_LOG_IOV_LIVE_MIGRATION_IMPORT_PREPARE_FAILED, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_ERROR_HIGH,
		"Live migration failed: Import preparation error."),
	add_entry(AMDGV_LOG_IOV_LIVE_MIGRATION_IMPORT_STATIC_FAILED, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_ERROR_HIGH,
		"Live migration failed: Import static data error."),
	add_entry(AMDGV_LOG_IOV_LIVE_MIGRATION_IMPORT_DYNAMIC_FAILED, LOG_DATA_ARG_NONE,
		AMDGV_LOG_SEVERITY_ERROR_HIGH,
		"Live migration failed: Import dynamic data error."),

	add_entry(AMDGV_LOG_IOV_EVENT_NOTIFICATION_NOT_SUPPORTED, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_WARNING, "Event notification is not supported."),
	add_entry(AMDGV_LOG_IOV_CSA_FB_MEM_NOT_ALLOCATED, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Private CSA FB memory is not allocated."),
	add_entry(AMDGV_LOG_IOV_READ_VF_FB_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Cannot read VF FB from PCIe config space."),
	add_entry(AMDGV_LOG_IOV_L1_SECURITY_DISABLED, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_INFO, "L1 security is disabled."),
	add_entry(AMDGV_LOG_IOV_MB_MSG_BUF_NOT_ALLOCATED, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Mailbox message data storage not allocated."),
	add_entry(AMDGV_LOG_IOV_MB_INVALID_IDX, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Invalid mailbox index %llu: does not belong to any VF or PF."),
	add_entry(AMDGV_LOG_IOV_MB_MSG_TOO_LONG, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_WARNING, "Mailbox message too long: only first %llu entries considered."),
	add_entry(AMDGV_LOG_IOV_MB_NOTIFY_GPU_DEBUG, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_DEBUG, "Notify VF GPU debug notification (completion=%llu)."),
	add_entry(AMDGV_LOG_IOV_MB_IRQ_SOURCE_ENABLE_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Unable to enable mailbox IRQ source: callback not implemented."),
	add_entry(AMDGV_LOG_IOV_IH_RING_NOT_ALLOCATED, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Interrupt manager ring is not allocated."),
	add_entry(AMDGV_LOG_IOV_IH_QUEUE_FULL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Interrupt handler queue is full."),
	add_entry(AMDGV_LOG_IOV_MB_INVALID_VF_EVENT, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_WARNING, "Invalid VF mailbox request (event id %llu)."),
	add_entry(AMDGV_LOG_IOV_PSP_VF_CMD_RELAY_OUT_OF_RANGE, LOG_DATA_ARG_32_32,
		  AMDGV_LOG_SEVERITY_WARNING, "Dropping PSP VF cmd relay; write pointer 0x%x out of range (max 0x%x)."),
	add_entry(AMDGV_LOG_IOV_UNSUPPORTED_CRIT_REGION_VER, LOG_DATA_ARG_32_32,
		  AMDGV_LOG_SEVERITY_WARNING, "VF sent unsupported crit region version %u; clamping to V%u."),
	add_entry(AMDGV_LOG_IOV_UNHANDLED_HV_INTR, LOG_DATA_ARG_32_32,
		  AMDGV_LOG_SEVERITY_WARNING, "Some host interrupts (0x%x) are not handled (mask 0x%x)."),
	add_entry(AMDGV_LOG_IOV_IP_DISCOVERY_UPLOAD_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_WARNING, "Failed to upload IP discovery data to VF."),
	add_entry(AMDGV_LOG_IOV_CPER_RECORD_OVERFLOW, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "CPER record %llu cannot fit in RAS telemetry region."),
	add_entry(AMDGV_LOG_IOV_UNSUPPORTED_CPER_EVENT, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_DEBUG, "Unsupported vfmgr CPER event id %llu."),
	add_entry(AMDGV_LOG_IOV_CRIT_REGION_NOT_INITIALIZED, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_WARNING, "VF critical region is not initialized."),
	add_entry(AMDGV_LOG_IOV_BAD_PAGE_IN_CRIT_REGION, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_INFO, "Bad page found in VF critical region (version id %llu); resetting region."),
	add_entry(AMDGV_LOG_IOV_CRIT_REGION_V1_DISABLED_BAD_PAGE, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_WARNING, "Disabling critical region V1 cap due to detected bad page."),
	add_entry(AMDGV_LOG_IOV_CRIT_REGION_BP_RESERVE_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to reserve bad page in VF critical region."),
	add_entry(AMDGV_LOG_IOV_CRIT_REGION_TABLE_ALLOC_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Dynamic allocation of VF critical-region table failed."),
	add_entry(AMDGV_LOG_IOV_CRIT_REGION_INIT_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_WARNING, "Failed to initialize VF critical region."),
	add_entry(AMDGV_LOG_IOV_VF2PF_CHECKSUM_MISMATCH, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_WARNING, "VF2PF message checksum mismatch; retries remaining %llu."),
	add_entry(AMDGV_LOG_IOV_VF2PF_UNTRUSTWORTHY_GUEST_INFO, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_WARNING, "Untrustworthy guest information in VF2PF message; dropping request."),
	add_entry(AMDGV_LOG_IOV_UPLOAD_FW_XCHG_DENIED, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Cannot upload FW to VF."),
	add_entry(AMDGV_LOG_IOV_MMIO_VF_NOT_CONFIGURED, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "VF not configured; dropping MMIO request."),
	add_entry(AMDGV_LOG_IOV_MMIO_VF_RES_NOT_MAPPED, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "VF resource not mapped; dropping MMIO request."),
	add_entry(AMDGV_LOG_IOV_GUEST_DRIVER_LOAD_DETECTED, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_DEBUG, "Detected guest driver load via FB_LOCATION_TOP write; releasing full access."),
	add_entry(AMDGV_LOG_IOV_ARBITRARY_VF_MEM_ACCESS_DENIED, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Cannot access arbitrary VF memory."),
	add_entry(AMDGV_LOG_IOV_INVALID_CRIT_REGION_VER, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Invalid VF critical region version %llu."),
	add_entry(AMDGV_LOG_IOV_UPLOAD_FW_TO_VF_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to upload firmware image to VF FB."),
	add_entry(AMDGV_LOG_IOV_BAD_PAGE_CRIT_REGION_COND_AVAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_INFO, "Bad page found in VF critical region (version id %llu); setting VF to conditionally available."),

	add_entry_ext(AMDGV_LOG_IOV_WS_FIRST_CMD_TIMEOUT, LOG_DATA_ARG_THREE_64_EXT,
		  AMDGV_LOG_SEVERITY_ERROR_LOW,
		  "Timeout waiting for world switch first command complete. mask=0x%llx elapsed=%llu us."),
	add_entry_ext(AMDGV_LOG_IOV_WS_CMD_TIMEOUT, LOG_DATA_ARG_THREE_64_EXT,
		  AMDGV_LOG_SEVERITY_ERROR_LOW,
		  "Timeout waiting for world switch command complete. hw_sched_id=%llu elapsed=%llu us."),
	add_entry(AMDGV_LOG_IOV_MB_TRN_MSG_ACK_TIMEOUT, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_INFO, "Timeout waiting for mailbox transaction message ack (elapsed %llu us)."),
	add_entry(AMDGV_LOG_IOV_GUEST_RESET_READY_TIMEOUT, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_WARNING, "Timeout waiting for guest reset ready (elapsed %llu us)."),

	/* this one is the MAX */
	add_entry(AMDGV_LOG_IOV_MAX, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_INFO,
		  "This is error log collect test for IOV component (test count %llu)."),
};

error_category(ECC) = {
	add_entry(AMDGV_LOG_ECC_UCE, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "Adapter(UMC) occurred %llu uncorrectable ECC error since GPU load."),
	add_entry(AMDGV_LOG_ECC_CE, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_LOW,
		  "Adapter(UMC) occurred %llu correctable ECC error since GPU load."),
	add_entry(
		AMDGV_LOG_ECC_IN_PF_FB, LOG_DATA_ARG_32_32, AMDGV_LOG_SEVERITY_ERROR_HIGH,
		"Bad Page Record #%u (of %u storage threshold) is within PF critical region, please follow AMD Service Action Guide."),
	add_entry(
		AMDGV_LOG_ECC_IN_CRI_REG, LOG_DATA_ARG_32_32, AMDGV_LOG_SEVERITY_ERROR_HIGH,
		"Bad Page Record #%u (of %u storage threshold) is within TMR or CSA or IPD Critical regions, please follow AMD Service Action Guide."),
	add_entry(
		AMDGV_LOG_ECC_IN_VF_CRI, LOG_DATA_ARG_32_32, AMDGV_LOG_SEVERITY_ERROR_HIGH,
		"Bad Page Record #%u (of %u storage threshold) is within VF critical region, please follow AMD Service Action Guide."),
	add_entry(AMDGV_LOG_ECC_REACH_THD, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_HIGH,
		  "ECC record reach threshold %llu pages, please follow AMD Service Action Guide."),
	add_entry(AMDGV_LOG_ECC_VF_CE, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_LOW,
		  "%llu correctable hardware error detected in UMC block."),
	add_entry(
		AMDGV_LOG_ECC_VF_UE, LOG_DATA_ARG_32_32, AMDGV_LOG_SEVERITY_ERROR_MED,
		"%u time out of %u threshold - uncorrectable hardware error detected in UMC block."),
	add_entry(
		AMDGV_LOG_ECC_IN_SAME_ROW, LOG_DATA_ARG_32_32, AMDGV_LOG_SEVERITY_ERROR_HIGH,
		"%u time out of %u threshold - ECC happens within same memory row, please follow AMD Service Action Guide."),

	add_entry(AMDGV_LOG_ECC_UMC_UE, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_MED,
		"%llu uncorrectable hardware error detected in UMC block."),
	add_entry(
		AMDGV_LOG_ECC_GFX_CE, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_LOW,
		"%llu correctable hardware error detected in GFX block."),
	add_entry(
		AMDGV_LOG_ECC_GFX_UE, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_MED,
		"%llu uncorrectable hardware error detected in GFX block."),
	add_entry(
		AMDGV_LOG_ECC_SDMA_CE, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_LOW,
		"%llu correctable hardware error detected in SDMA block."),
	add_entry(
		AMDGV_LOG_ECC_SDMA_UE, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_MED,
		"%llu uncorrectable hardware error detected in SDMA block."),

	add_entry(AMDGV_LOG_ECC_GFX_CE_TOTAL, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_INFO,
		  "Adapter(GFX) occurred %llu correctable ECC error since GPU load."),
	add_entry(AMDGV_LOG_ECC_GFX_UE_TOTAL, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_INFO,
		  "Adapter(GFX) occurred %llu uncorrectable ECC error since GPU load."),
	add_entry(AMDGV_LOG_ECC_SDMA_CE_TOTAL, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_INFO,
		  "Adapter(SDMA) occurred %llu correctable ECC error since GPU load."),
	add_entry(AMDGV_LOG_ECC_SDMA_UE_TOTAL, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_INFO,
		  "Adapter(SDMA) occurred %llu uncorrectable ECC error since GPU load."),
	add_entry(AMDGV_LOG_ECC_UMC_CE_TOTAL, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_INFO,
		  "Adapter(UMC) occurred %llu correctable ECC error since GPU load."),
	add_entry(AMDGV_LOG_ECC_UMC_UE_TOTAL, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_INFO,
		  "Adapter(UMC) occurred %llu uncorrectable ECC error since GPU load."),
	add_entry(
		AMDGV_LOG_ECC_MMHUB_CE, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_WARNING,
		"%llu correctable hardware error detected in MMHUB block."),
	add_entry(
		AMDGV_LOG_ECC_MMHUB_UE, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_MED,
		"%llu uncorrectable hardware error detected in MMHUB block."),
	add_entry(AMDGV_LOG_ECC_MMHUB_CE_TOTAL, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_INFO,
		  "Adapter(MMHUB) occurred %llu correctable ECC error since GPU load."),
	add_entry(AMDGV_LOG_ECC_MMHUB_UE_TOTAL, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_INFO,
		  "Adapter(MMHUB) occurred %llu uncorrectable ECC error since GPU load."),

	add_entry(
		AMDGV_LOG_ECC_XGMI_WAFL_CE, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_WARNING,
		"%llu correctable hardware error detected in XGMI block."),
	add_entry(
		AMDGV_LOG_ECC_XGMI_WAFL_UE, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_MED,
		"%llu uncorrectable hardware error detected in XGMI block."),
	add_entry(AMDGV_LOG_ECC_XGMI_WAFL_CE_TOTAL, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_INFO,
		  "Adapter(XGMI) occurred %llu correctable ECC error since GPU load."),
	add_entry(AMDGV_LOG_ECC_XGMI_WAFL_UE_TOTAL, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_INFO,
		  "Adapter(XGMI) occurred %llu uncorrectable ECC error since GPU load."),

	add_entry(AMDGV_LOG_ECC_FATAL_ERROR, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_MED,
		"GPU detected ECC Fatal Error."),
	add_entry(AMDGV_LOG_ECC_POISON_CONSUMPTION, LOG_DATA_ARG_32_32, AMDGV_LOG_SEVERITY_ERROR_LOW,
		"RAS poison consumption triggered by VF%u, RAS block:%u."),

	add_entry_ext(AMDGV_LOG_ECC_ACA_DUMP, LOG_DATA_ARG_FIVE_64_EXT, AMDGV_LOG_SEVERITY_INFO,
		  "Acceleration Check Architecture event logged:\nSTATUS=0x%016llx\nADDR=0x%016llx\nMISC0=0x%016llx\nIPID=0x%016llx\nSYND=0x%016llx"),
	add_entry(AMDGV_LOG_ECC_WRONG_SOCKET_ID, LOG_DATA_ARG_32_32, AMDGV_LOG_SEVERITY_ERROR_LOW,
		"The socket id reported from ACA is different from the socket id detected by driver. ACA:%u, driver:%u"),
	add_entry(AMDGV_LOG_ECC_ACA_UNKNOWN_BLOCK_INSTANCE, LOG_DATA_ARG_16_16_32, AMDGV_LOG_SEVERITY_ERROR_LOW,
		"Maximum instance from ACA ras block %u exceeds the driver maximum. ACA:%u, driver:%u"),

	add_entry(AMDGV_LOG_ECC_UNKNOWN_CHIPLET_CE, LOG_DATA_ARG_16_16_16_16, AMDGV_LOG_SEVERITY_WARNING,
		"socket: %u, die: %u, %u new correctable hardware errors detected in UNKNOWN Block. %u total UNKNOWN Block correctable ECC errors since GPU load."),
	add_entry(AMDGV_LOG_ECC_UNKNOWN_CHIPLET_UE, LOG_DATA_ARG_16_16_16_16, AMDGV_LOG_SEVERITY_ERROR_MED,
		"socket: %u, die: %u, %u new uncorrectable hardware errors detected in UNKNOWN Block. %u total UNKNOWN Block uncorrectable ECC errors since GPU load."),
	add_entry(AMDGV_LOG_ECC_UMC_CHIPLET_CE, LOG_DATA_ARG_16_16_16_16, AMDGV_LOG_SEVERITY_WARNING,
		"socket: %u, die: %u, %u new correctable hardware errors detected in UMC Block. %u total UMC Block correctable ECC errors since GPU load."),
	add_entry(AMDGV_LOG_ECC_UMC_CHIPLET_UE, LOG_DATA_ARG_16_16_16_16, AMDGV_LOG_SEVERITY_ERROR_MED,
		"socket: %u, die: %u, %u new uncorrectable hardware errors detected in UMC Block. %u total UMC Block uncorrectable ECC errors since GPU load."),
	add_entry(AMDGV_LOG_ECC_GFX_CHIPLET_CE, LOG_DATA_ARG_16_16_16_16, AMDGV_LOG_SEVERITY_WARNING,
		"socket: %u, die: %u, %u new correctable hardware errors detected in GFX Block. %u total GFX Block correctable ECC errors since GPU load."),
	add_entry(AMDGV_LOG_ECC_GFX_CHIPLET_UE, LOG_DATA_ARG_16_16_16_16, AMDGV_LOG_SEVERITY_ERROR_MED,
		"socket: %u, die: %u, %u new uncorrectable hardware errors detected in GFX Block. %u total GFX Block uncorrectable ECC errors since GPU load."),
	add_entry(AMDGV_LOG_ECC_SDMA_CHIPLET_CE, LOG_DATA_ARG_16_16_16_16, AMDGV_LOG_SEVERITY_WARNING,
		"socket: %u, die: %u, %u new correctable hardware errors detected in SDMA Block. %u total SDMA Block correctable ECC errors since GPU load."),
	add_entry(AMDGV_LOG_ECC_SDMA_CHIPLET_UE, LOG_DATA_ARG_16_16_16_16, AMDGV_LOG_SEVERITY_ERROR_MED,
		"socket: %u, die: %u, %u new uncorrectable hardware errors detected in SDMA Block. %u total SDMA Block uncorrectable ECC errors since GPU load."),
	add_entry(AMDGV_LOG_ECC_MMHUB_CHIPLET_CE, LOG_DATA_ARG_16_16_16_16, AMDGV_LOG_SEVERITY_WARNING,
		"socket: %u, die: %u, %u new correctable hardware errors detected in MMHUB Block. %u total MMHUB Block correctable ECC errors since GPU load."),
	add_entry(AMDGV_LOG_ECC_MMHUB_CHIPLET_UE, LOG_DATA_ARG_16_16_16_16, AMDGV_LOG_SEVERITY_ERROR_MED,
		"socket: %u, die: %u, %u new uncorrectable hardware errors detected in MMHUB Block. %u total MMHUB Block uncorrectable ECC errors since GPU load."),
	add_entry(AMDGV_LOG_ECC_XGMI_WAFL_CHIPLET_CE, LOG_DATA_ARG_16_16_16_16, AMDGV_LOG_SEVERITY_WARNING,
		"socket: %u, die: %u, %u new correctable hardware errors detected in XGMI Block. %u total XGMI Block correctable ECC errors since GPU load."),
	add_entry(AMDGV_LOG_ECC_XGMI_WAFL_CHIPLET_UE, LOG_DATA_ARG_16_16_16_16, AMDGV_LOG_SEVERITY_ERROR_MED,
		"socket: %u, die: %u, %u new uncorrectable hardware errors detected in XGMI Block. %u total XGMI Block uncorrectable ECC errors since GPU load."),
	add_entry(AMDGV_LOG_ECC_BAD_PAGE_ENTRIES_FOUND, LOG_DATA_ARG_32_32, AMDGV_LOG_SEVERITY_INFO,
		"driver RAS bad page storage has %u bad page records of %u threshold."),

	add_entry(AMDGV_LOG_ECC_UMC_DE, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_WARNING,
		"%llu deferred hardware error detected in UMC block."),
	add_entry(AMDGV_LOG_ECC_UMC_DE_TOTAL, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_INFO,
		  "Adapter(UMC) occurred %llu deferred ECC error since GPU load."),

	add_entry(AMDGV_LOG_ECC_UNKNOWN, LOG_DATA_ARG_16_16_32, AMDGV_LOG_SEVERITY_ERROR_LOW,
		"socket: %u, %u new hardware errors detected in UNKNOWN Block. %u total UNKNOWN Block ECC errors since GPU load."),

	add_entry(AMDGV_LOG_ECC_EEPROM_REACH_THD, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_HIGH,
		  "RAS EEPROM cannot hold anymore bad page records, please RMA this GPU."),

	add_entry(AMDGV_LOG_ECC_UMC_CHIPLET_DE, LOG_DATA_ARG_16_16_16_16, AMDGV_LOG_SEVERITY_WARNING,
		"socket: %u, die: %u, %u new deferred hardware errors detected in UMC Block. %u total UMC Block deferred ECC errors since GPU load."),

	add_entry(AMDGV_LOG_ECC_UNKNOWN_CHIPLET_DE, LOG_DATA_ARG_16_16_16_16, AMDGV_LOG_SEVERITY_ERROR_LOW,
		"socket: %u, die: %u, %u new deferred hardware errors detected in UNKNOWN Block. %u total UNKNOWN Block deferred ECC errors since GPU load."),

	add_entry(AMDGV_LOG_ECC_EEPROM_CHK_MISMATCH, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_LOW,
		"RAS EEPROM Table checksum mismatch detected."),
	add_entry(AMDGV_LOG_ECC_EEPROM_RESET, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_WARNING,
		"RAS EEPROM Table is reset."),
	add_entry(AMDGV_LOG_ECC_EEPROM_RESET_FAILED, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_LOW,
		"RAS EEPROM Table reset failed."),

	add_entry(AMDGV_LOG_ECC_EEPROM_APPEND, LOG_DATA_ARG_32_32, AMDGV_LOG_SEVERITY_INFO,
		"%u EEPROM records were appended to RAS EEPROM table. There are %u records now."),
	add_entry(AMDGV_LOG_ECC_THD_CHANGED, LOG_DATA_ARG_32_32, AMDGV_LOG_SEVERITY_INFO,
		"RAS EEPROM table bad page threshold has changed. Old threshold = %u. New threshold %u."),
	add_entry(AMDGV_LOG_ECC_DUP_ENTRIES, LOG_DATA_ARG_32_32, AMDGV_LOG_SEVERITY_INFO,
		"Duplicate bad page records detected. Old count = %d, new count = %d. Overwriting RAS EEPROM table."),
	add_entry(AMDGV_LOG_ECC_EEPROM_WRONG_HDR, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_INFO,
		"Uninitialized RAS EEPROM table detected."),
	add_entry(AMDGV_LOG_ECC_EEPROM_WRONG_VER, LOG_DATA_ARG_32_32, AMDGV_LOG_SEVERITY_ERROR_LOW,
		"Wrong RAS EEPROM table version detected. Table version = 0x%x. Expected version = 0x%x"),
	add_entry(AMDGV_LOG_ECC_BAD_PAGE_APPEND, LOG_DATA_ARG_32_32, AMDGV_LOG_SEVERITY_INFO,
		"%u bad page records were appended to driver RAS bad page storage. There are %u records now."),

	add_entry(AMDGV_LOG_ECC_VCN_CHIPLET_CE, LOG_DATA_ARG_16_16_16_16, AMDGV_LOG_SEVERITY_WARNING,
		"socket: %u, die: %u, %u new correctable hardware errors detected in VCN Block. %u total VCN Block correctable ECC errors since GPU load."),
	add_entry(AMDGV_LOG_ECC_VCN_CHIPLET_UE, LOG_DATA_ARG_16_16_16_16, AMDGV_LOG_SEVERITY_ERROR_MED,
		"socket: %u, die: %u, %u new uncorrectable hardware errors detected in VCN Block. %u total VCN Block uncorrectable ECC errors since GPU load."),
	add_entry(AMDGV_LOG_ECC_JPEG_CHIPLET_CE, LOG_DATA_ARG_16_16_16_16, AMDGV_LOG_SEVERITY_WARNING,
		"socket: %u, die: %u, %u new correctable hardware errors detected in JPEG Block. %u total JPEG Block correctable ECC errors since GPU load."),
	add_entry(AMDGV_LOG_ECC_JPEG_CHIPLET_UE, LOG_DATA_ARG_16_16_16_16, AMDGV_LOG_SEVERITY_ERROR_MED,
		"socket: %u, die: %u, %u new uncorrectable hardware errors detected in JPEG Block. %u total JPEG Block uncorrectable ECC errors since GPU load."),
	add_entry(AMDGV_LOG_ECC_EEPROM_VERSION_PARSE_FAILED, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_WARNING,
		"RAS EEPROM table Version parse failed."),
	add_entry(AMDGV_LOG_ECC_EEPROM_CONFIG_BP_THD_NOT_SUPPORTED, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_WARNING,
		"RAS EEPROM table configurable bad page threshold is not supported. Bad page threshold is set to default value."),
	add_entry(AMDGV_LOG_ECC_MMSCH_CHIPLET_CE, LOG_DATA_ARG_16_16_16_16, AMDGV_LOG_SEVERITY_WARNING,
		"socket: %u, die: %u, %u new correctable hardware errors detected in MMSCH Block. %u total MMSCH Block correctable ECC errors since GPU load."),
	add_entry(AMDGV_LOG_ECC_MMSCH_CHIPLET_UE, LOG_DATA_ARG_16_16_16_16, AMDGV_LOG_SEVERITY_ERROR_MED,
		"socket: %u, die: %u, %u new uncorrectable hardware errors detected in MMSCH Block. %u total MMSCH Block uncorrectable ECC errors since GPU load."),
	add_entry(AMDGV_LOG_ECC_RAS_INTR_TIMEOUT, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_LOW,
		"Timeout waiting for RAS interrupt (elapsed %llu us)."),
	/* this one is the MAX */
	add_entry(AMDGV_LOG_ECC_MAX, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_INFO,
		  "This is error log collect test for ECC component (test count %llu)."),
};

error_category(PP) = {
	add_entry(AMDGV_LOG_PP_SET_DPM_POLICY_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Set virtualization GFX DPM policy failed."),
	add_entry(AMDGV_LOG_PP_ACTIVATE_DPM_POLICY_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Activate virtualization GFX DPM policy failed."),
	add_entry(AMDGV_LOG_PP_I2C_SLAVE_NOT_PRESENT, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_INFO, "I2C slave at 0x%llX is not present."),
	add_entry(AMDGV_LOG_PP_THROTTLER_EVENT, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_WARNING, "GPU device throttler event detected: 0x%016llx."),
	add_entry(AMDGV_LOG_PP_MODE2_RESET_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "PMFW failed mode 2 reset."),
	add_entry(AMDGV_LOG_PP_MODE0_RESET_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "PMFW failed mode 0 reset."),
	/* this one is the MAX */
	add_entry(AMDGV_LOG_PP_MAX, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_INFO,
		  "This is error log collect test for PP component (test count %llu)."),
};

error_category(SCHED) = {
	add_entry(AMDGV_LOG_SCHED_WORLD_SWITCH_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "World Switch Failed!"),
	add_entry(AMDGV_LOG_SCHED_DISABLE_AUTO_HW_SWITCH_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED,
		  "DISABLE_AUTO_HW_SCHEDULING_AND_CONTEXT_SWITCH failed."),
	add_entry(AMDGV_LOG_SCHED_ENABLE_AUTO_HW_SWITCH_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "ENABLE_AUTO_HW_SWITCH failed on block %llu."),
	add_entry(AMDGV_LOG_SCHED_GFX_SAVE_REG_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "GFX SAVE register failed."),
	add_entry(AMDGV_LOG_SCHED_GFX_IDLE_REG_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "GFX IDLE register failed."),

	add_entry(AMDGV_LOG_SCHED_GFX_RUN_REG_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "GFX RUN register failed."),
	add_entry(AMDGV_LOG_SCHED_GFX_LOAD_REG_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "GFX LOAD register failed."),
	add_entry(AMDGV_LOG_SCHED_GFX_INIT_REG_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "GFX INIT register failed."),
	add_entry(AMDGV_LOG_SCHED_MM_SAVE_REG_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "MM SAVE register failed."),
	add_entry(AMDGV_LOG_SCHED_MM_IDLE_REG_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "MM IDLE register failed."),

	add_entry(AMDGV_LOG_SCHED_MM_RUN_REG_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "MM RUN register failed."),
	add_entry(AMDGV_LOG_SCHED_MM_LOAD_REG_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "MM LOAD register failed."),
	add_entry(AMDGV_LOG_SCHED_MM_INIT_REG_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "MM INIT register failed."),
	add_entry(AMDGV_LOG_SCHED_INIT_GPU_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "INIT_GPU failed on block %llu."),
	add_entry(AMDGV_LOG_SCHED_RUN_GPU_FAIL, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_LOW,
		  "RUN_GPU failed on block %llu."),

	add_entry(AMDGV_LOG_SCHED_SAVE_GPU_STATE_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "SAVE_GPU_STATE failed on block %llu."),
	add_entry(AMDGV_LOG_SCHED_LOAD_GPU_STATE_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "LOAD_GPU_STATE failed on block %llu."),
	add_entry(AMDGV_LOG_SCHED_IDLE_GPU_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "IDLE_GPU failed on block %llu."),
	add_entry(AMDGV_LOG_SCHED_FINI_GPU_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "FINI_GPU failed on block %llu."),
	add_entry(AMDGV_LOG_SCHED_DEAD_VF, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "VF%llu is not responding."),

	add_entry(AMDGV_LOG_SCHED_EVENT_QUEUE_FULL, LOG_DATA_ARG_32_32,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Sched event queue is full. rptr(%u) wptr(%u)."),
	add_entry(AMDGV_LOG_SCHED_SHUTDOWN_VF_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Cannot shutdown VF%u."),
	add_entry(AMDGV_LOG_SCHED_RESET_VF_NUM_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "VF%u is still available in scheduler."),
	add_entry(AMDGV_LOG_SCHED_IGNORE_EVENT, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_WARNING,
		  "Ignore schedule event 0x%llx."),
	add_entry(AMDGV_LOG_SCHED_PF_SWITCH_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Switch to PF Failed!"),

	add_entry(AMDGV_LOG_SCHED_INVALID_HW_SCHED_ID, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Invalid hw scheduler id %llu for this operation."),
	add_entry(AMDGV_LOG_SCHED_AUTO_SCHED_STOP_TIMEOUT, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_WARNING, "Failed to wait for auto scheduler (hw sched id %llu) to stop."),
	add_entry_ext(AMDGV_LOG_SCHED_RLCG_VF_INTF_FAIL, LOG_DATA_ARG_THREE_64_EXT,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "RLCG VFi interface failed (xcc_id %llu, rsp 0x%llx, msg.result 0x%llx)."),
	add_entry(AMDGV_LOG_SCHED_GFX_MODE_NOT_SUPPORTED, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_WARNING, "GFX sched mode id %llu is not supported on current asic."),
	add_entry(AMDGV_LOG_SCHED_INVALID_XCC_NUM, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Invalid or unsupported XCC number: %llu."),
	add_entry(AMDGV_LOG_SCHED_PARTITION_FULL_ACCESS_DISABLED, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_DEBUG, "Partition full access is disabled."),
	add_entry(AMDGV_LOG_SCHED_FULL_ACCESS_TIME_CHANGED, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_DEBUG, "Allowed time for full access changed to %llums."),
	add_entry(AMDGV_LOG_SCHED_SET_VF_FB, LOG_DATA_ARG_32_32,
		  AMDGV_LOG_SEVERITY_DEBUG, "Set VF FB: offset %u MB, size %u MB."),
	add_entry(AMDGV_LOG_SCHED_CTX_EMPTY_INTR_GATE, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_DEBUG, "Context-empty interrupt gate from RLC (enabled=%llu)."),
	add_entry(AMDGV_LOG_SCHED_LIVE_MIGRATION_NOT_SUPPORTED, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Live migration (transfer VF data) is not supported."),
	add_entry(AMDGV_LOG_SCHED_NO_ABNORMAL_ENGINE, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_INFO, "No engine in abnormal state, skipping reset."),
	add_entry(AMDGV_LOG_SCHED_RESET_AUTO_ENGINE_HUNG, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_WARNING, "Starting auto reset: engine hung (sched block id %llu)."),
	add_entry(AMDGV_LOG_SCHED_PF_HUNG_WGR, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_WARNING, "PF is the active function on the hung engine."),
	add_entry(AMDGV_LOG_SCHED_HUNG_ENGINE_INVALID_VF, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_INFO, "Invalid VF index (%llu) on hung engine."),
	add_entry(AMDGV_LOG_SCHED_HW_SCHED_NO_LOGICAL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_INFO, "HW scheduler (id %llu) does not belong to any logical scheduler."),

	/* this one is the MAX */
	add_entry(AMDGV_LOG_SCHED_MAX, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_INFO,
		  "This is error log collect test for SCHED component (test count %llu)."),
};

error_category(VF) = {
	add_entry(AMDGV_LOG_VF_ATOMBIOS_INIT_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "amdgpu_atombios_init failed."),
	add_entry(AMDGV_LOG_VF_NO_VBIOS, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_LOW,
		  "no vBIOS found."),
	add_entry(AMDGV_LOG_VF_GPU_POST_ERROR, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "gpu post error."),
	add_entry(AMDGV_LOG_VF_ATOMBIOS_GET_CLOCK_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "amdgpu_atombios_get_clock_info failed."),
	add_entry(AMDGV_LOG_VF_FENCE_INIT_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "amdgpu_fence_driver_init failed."),

	add_entry(AMDGV_LOG_VF_AMDGPU_INIT_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "amdgpu_init failed."),
	add_entry(AMDGV_LOG_VF_IB_INIT_FAIL, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_LOW,
		  "IB initialization failed (%d)."),
	add_entry(AMDGV_LOG_VF_AMDGPU_LATE_INIT_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "amdgpu_late_init failed."),
	add_entry(AMDGV_LOG_VF_ASIC_RESUME_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "asic resume failed (%d)."),
	add_entry(AMDGV_LOG_VF_GPU_RESET_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "GPU reset failed."),
	add_entry(AMDGV_LOG_VF_XCHG_REGION_INVALID_SIZE, LOG_DATA_ARG_32_32,
		  AMDGV_LOG_SEVERITY_ERROR_LOW,
		  "XCHG region rejected: invalid size (requested 0x%x, max 0x%x)."),
	add_entry(AMDGV_LOG_VF_XCHG_REGION_NOT_INITIALIZED, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "VF exchange region is not initialized."),
	add_entry(AMDGV_LOG_VF_XCHG_TABLE_TARGET_INVALID, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "VF exchange table target is invalid."),

	/* this one is the MAX */
	add_entry(AMDGV_LOG_VF_MAX, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_INFO,
		  "This is error log collect test for VF component (test count %llu)."),
};

error_category(VBIOS) = {
	add_entry(AMDGV_LOG_VBIOS_INVALID, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_HIGH,
		  "Invalid VBios."),
	add_entry(AMDGV_LOG_VBIOS_IMAGE_MISSING, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "VBios image is missing."),
	add_entry(AMDGV_LOG_VBIOS_CHECKSUM_ERR, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "VBios checksum error."),
	add_entry(AMDGV_LOG_VBIOS_POST_FAIL, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_HIGH,
		  "Post VBIOS failed."),
	add_entry(AMDGV_LOG_VBIOS_READ_FAIL, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_HIGH,
		  "Read VBIOS failed."),

	add_entry(AMDGV_LOG_VBIOS_READ_IMG_HEADER_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "Read ROM image header failed."),
	add_entry(AMDGV_LOG_VBIOS_READ_IMG_SIZE_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "ATOM read ROM image size failed."),
	add_entry(AMDGV_LOG_VBIOS_GET_FW_INFO_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "ATOM get firmware info failed."),
	add_entry(AMDGV_LOG_VBIOS_GET_TBL_REVISION_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "ATOM get table revision failed."),
	add_entry(AMDGV_LOG_VBIOS_PARSER_TBL_FAIL, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "ATOM parse table failed! (parser result=%llu)."),

	add_entry(AMDGV_LOG_VBIOS_IP_DISCOVERY_FAIL, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "IP Discovery Failure"),
	add_entry(AMDGV_LOG_VBIOS_TIMEOUT, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_HIGH,
		  "Read VBios timeout."),
	add_entry(AMDGV_LOG_VBIOS_IP_DISCOVERY_BINARY_CHECKSUM_FAIL, LOG_DATA_ARG_32_32,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "IP Discovery Binary checksum failed expected=0x%08x readback=0x%08x"),
	add_entry(AMDGV_LOG_VBIOS_IP_DISCOVERY_TABLE_CHECKSUM_FAIL, LOG_DATA_ARG_16_16_32,
		  AMDGV_LOG_SEVERITY_ERROR_HIGH, "IP Discovery Table %d checksum failed expected=0x%08x readback=0x%08x"),

	/* this one is the MAX */
	add_entry(AMDGV_LOG_VBIOS_MAX, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_INFO,
		  "This is error log collect test for VBIOS component (test count %llu)."),
};

error_category(GPU) = {
	add_entry(AMDGV_LOG_GPU_DEVICE_LOST, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_HIGH,
		  "Device disappeared from bus."),
	add_entry(AMDGV_LOG_GPU_NOT_SUPPORTED, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "The device id (0x%llx) is not supported by this LibGV."),
	add_entry(AMDGV_LOG_GPU_RMA, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_HIGH,
		  "GPU is in RMA state."),
	add_entry(AMDGV_LOG_GPU_NOT_INITIALIZED, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Not initialized."),
	add_entry(AMDGV_LOG_GPU_MMSCH_ABNORMAL_STATE, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "Multimedia virtualization scheduler has entered an abnormal state"),
	add_entry(AMDGV_LOG_GPU_RLCV_ABNORMAL_STATE, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "Graphics Virtualization Scheduler has entered an abnormal state"),
	add_entry(AMDGV_LOG_GPU_SDMA_ENGINE_BUSY, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_INFO,
		  "System DMA engine is busy"),
	add_entry(AMDGV_LOG_GPU_RLC_ENGINE_BUSY, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_INFO,
		  "Run List Controller is busy"),
	add_entry(AMDGV_LOG_GPU_GC_ENGINE_BUSY, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_INFO,
		  "Graphics-Compute is busy"),
	add_entry(AMDGV_LOG_GPU_HIVE_RMA, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_HIGH,
			"Driver disabled runtime services because it is FB sharing with GPU(s) that are in RMA state."
			" Disable FB sharing or Replace the RMA GPU(s) to restore the hive."),
	add_entry(AMDGV_LOG_GPU_UTCL2_BUSY, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_WARNING,
		  "UTCL2 shows busy after VF FLR (GRBM_STATUS2 0x%llx)."),
	add_entry(AMDGV_LOG_GPU_UTCL2_HANG, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "UTCL2 is likely hung after VF FLR (GCVM_L2_STATUS 0x%llx)."),
	add_entry(AMDGV_LOG_GPU_GL2C_ERROR_DETECTED, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_WARNING,
		  "GL2C error detected."),
	add_entry(AMDGV_LOG_GPU_GC_SOFT_RESET_VMID_TIMEOUT, LOG_DATA_ARG_NONE, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "GC soft reset timed out waiting for CP_VMID_RESET to clear."),
	add_entry_ext(AMDGV_LOG_GPU_REG_WAIT_TIMEOUT, LOG_DATA_ARG_FIVE_64_EXT, AMDGV_LOG_SEVERITY_WARNING,
		  "Timeout waiting for register [0x%llx]. check_ne=%llu expect=0x%llx actual=0x%llx elapsed=%llu us."),
	add_entry(AMDGV_LOG_GPU_FB_HASH_TIMEOUT, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_LOW,
		  "Timeout waiting for FB hash done (elapsed %llu us)."),
	/* this one is the MAX */
	add_entry(AMDGV_LOG_GPU_MAX, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_INFO,
		  "This is error log collect test for GPU component (test count %llu)."),
};

error_category(GUARD) = {
	add_entry(AMDGV_LOG_GUARD_RESET_FAIL, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_MED,
		  "Failed to reset VF%llu guard info."),
	add_entry(AMDGV_LOG_GUARD_EVENT_OVERFLOW, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_WARNING, "Event 0x%llx overflow."),

	/* this one is the MAX */
	add_entry(AMDGV_LOG_GUARD_MAX, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_INFO,
		  "This is error log collect test for GUARD component (test count %llu)."),
};

error_category(GPUMON) = {
	add_entry(AMDGV_LOG_GPUMON_INVALID_OPTION, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Invalid VF option (%d)."),
	add_entry(AMDGV_LOG_GPUMON_INVALID_VF_INDEX, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Invalid VF index (%u)."),
	add_entry(AMDGV_LOG_GPUMON_INVALID_FB_SIZE, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Invalid FB size (%uMB)."),
	add_entry(AMDGV_LOG_GPUMON_NO_SUITABLE_SPACE, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "No suitable space to fit FB size (%uMB)."),
	add_entry(AMDGV_LOG_GPUMON_NO_AVAILABLE_SLOT, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "No available slot to allocate new VF."),

	add_entry(AMDGV_LOG_GPUMON_OVERSIZE_ALLOCATION, LOG_DATA_ARG_32_32,
		  AMDGV_LOG_SEVERITY_ERROR_LOW,
		  "FB offset (%uMB) plus FB size (%uMB) exceed total FB size."),
	add_entry(AMDGV_LOG_GPUMON_OVERLAPPING_FB, LOG_DATA_ARG_32_32,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Overlapped FB from (%uMB) to (%uMB)."),
	add_entry(AMDGV_LOG_GPUMON_INVALID_GFX_TIMESLICE, LOG_DATA_ARG_32_32,
		  AMDGV_LOG_SEVERITY_ERROR_LOW,
		  "Invalid GFX time slice value (%ums), Max allowance is (%ums)."),
	add_entry(AMDGV_LOG_GPUMON_INVALID_MM_TIMESLICE, LOG_DATA_ARG_32_32,
		  AMDGV_LOG_SEVERITY_ERROR_LOW,
		  "Invalid MM time slice value (%ums), Max allowance is (%ums)."),
	add_entry(AMDGV_LOG_GPUMON_INVALID_GFX_PART, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Invalid GFX time partition."),

	add_entry(AMDGV_LOG_GPUMON_VF_BUSY, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_ERROR_LOW,
		  "VF(%u) has loaded guest driver."),
	add_entry(AMDGV_LOG_GPUMON_INVALID_VF_NUM, LOG_DATA_ARG_32_32,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "VF num (%u) exceeds max allowance (%u)."),
	add_entry(AMDGV_LOG_GPUMON_NOT_SUPPORTED, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "API not supported by GPUMON."),
	add_entry(AMDGV_LOG_GPUMON_SET_ALREADY, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_WARNING, "Already set to specified mode."),
	add_entry(AMDGV_LOG_GPUMON_INVALID_MODE, LOG_DATA_ARG_NONE,
		  AMDGV_LOG_SEVERITY_ERROR_LOW, "Specified mode is invalid."),

	add_entry(AMDGV_LOG_GPUMON_FB_INFO, LOG_DATA_ARG_32_32,
		  AMDGV_LOG_SEVERITY_INFO, "Total FB available = %u MB, max usable FB size = %u MB."),

	/* this one is the MAX */
	add_entry(AMDGV_LOG_GPUMON_MAX, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_INFO,
		  "This is error log collect test for GPUMON component (test count %llu)."),
};

error_category(MMSCH) = {
	add_entry(AMDGV_LOG_MMSCH_IGNORED_JOB, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_WARNING,
		  "On this VF, there is least 1 job that is ignored on VCN(%u)."),
	add_entry(AMDGV_LOG_MMSCH_UNSUPPORTED_VCN_FW, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_LOW,
		  "On this VF, VCN(%u) FW does not support MM bandwidth managment."),

	/* this one is the MAX */
	add_entry(AMDGV_LOG_MMSCH_MAX, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_INFO,
		  "This is error log collect test for GPUMON component (test count %llu)."),
};

error_category(XGMI) = {
	add_entry(AMDGV_LOG_XGMI_TOPOLOGY_UPDATE_FAILED, LOG_DATA_ARG_NONE,
			AMDGV_LOG_SEVERITY_ERROR_HIGH, "Device failed to update XGMI Topology."),
	add_entry(AMDGV_LOG_XGMI_TOPOLOGY_HW_INIT_UPDATE, LOG_DATA_ARG_NONE,
			AMDGV_LOG_SEVERITY_INFO, "Last initialized device in hive initiating XGMI Topology update."),
	add_entry(AMDGV_LOG_XGMI_TOPOLOGY_UPDATE_DONE, LOG_DATA_ARG_NONE,
			AMDGV_LOG_SEVERITY_INFO, "Device successfully updated XGMI Topology."),
	add_entry(AMDGV_LOG_XGMI_FB_SHARING_SETTING_ERROR, LOG_DATA_ARG_NONE,
			AMDGV_LOG_SEVERITY_ERROR_MED, "Device has invalid XGMI FB Sharing setting."),
	add_entry(AMDGV_LOG_XGMI_FB_SHARING_SETTING_RESET, LOG_DATA_ARG_NONE,
			AMDGV_LOG_SEVERITY_ERROR_MED, "XGMI Hive FB Sharing settings have been reset due to errors."),
	add_entry(AMDGV_LOG_XGMI_CHAIN_RESET_NOTIFY, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_DEBUG, "Notifying chain reset on node 0x%llx."),
	add_entry(AMDGV_LOG_XGMI_CHAIN_RESET_NOTIFY_FAILED, LOG_DATA_ARG_64,
		  AMDGV_LOG_SEVERITY_ERROR_MED, "Failed to notify chain reset on node 0x%llx."),

		/* this one is the MAX */
	add_entry(AMDGV_LOG_XGMI_MAX, LOG_DATA_ARG_64, AMDGV_LOG_SEVERITY_INFO,
		  "This is error log collect test for XGMI component (test count %llu)."),
};

/* Error category */
const struct amdgv_log_info amdgv_log_list[AMDGV_LOG_CATEGORY_MAX] = {
	category_not_used(),  add_category(DRIVER), add_category(RESET), add_category(SCHED),
	add_category(VBIOS),  add_category(ECC),    add_category(PP),	 add_category(IOV),
	add_category(VF),     add_category(FW),	    add_category(GPU),	 add_category(GUARD),
	add_category(GPUMON), add_category(MMSCH),  add_category(XGMI),
};
