#!/bin/bash

# Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE COPYRIGHT HOLDER(S) OR AUTHOR(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

cd "$(dirname "${BASH_SOURCE[0]}")/../"
if [ -f "./VERSION" ]; then
    head -1 ./VERSION
    exit
elif [ -e "./.git" ] && [ "$(git rev-parse --is-inside-work-tree)" = "true" ]; then
    branch="$(git rev-parse --abbrev-ref HEAD)"
    if [ "$branch" = "mainline" ]; then
        name="$(git describe --long --match "mainline/*.*.*.K" 2>/dev/null)"
    fi
    if [ -z "$name" ]; then
        name="$(git describe --long --match "staging/*.*.*.K" 2>/dev/null)"
    fi
    ver="${name##*/}"
    if [ -n "$ver" ]; then
        echo "$ver"
        exit
    fi
fi

echo "Cannot detect version, using fallback version 0.0.0.K" 1>&2
echo "0.0.0.K"
