# Copyright Advanced Micro Devices, Inc.
#
# SPDX-License-Identifier: MIT


# GLOBAL CONFIG
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED True)
set(CMAKE_CXX_EXTENSIONS OFF)

# SMI CLI DEFINES
set(PROJECT_ROOT ${CMAKE_CURRENT_SOURCE_DIR})
set(BUILD_DIR ${PROJECT_ROOT}/build)
set(SOURCE_DIR ${PROJECT_ROOT}/src)
set(INCLUDE_DIR ${PROJECT_ROOT}/inc)
set(THIRD_PARTY_INCLUDE_DIR ${PROJECT_ROOT}/utils/third_party/inc)
set(INTERFACE_DIR ${PROJECT_ROOT}/../../interface)

# ADD COMPILER AND LINKER FLAGS
if(DEFINED AMD_SMI_NIC_SUPPORT)
    if(AMD_SMI_NIC_SUPPORT STREQUAL "True" OR AMD_SMI_NIC_SUPPORT)
        add_compile_definitions(AMD_SMI_NIC_SUPPORT)
    endif()
endif()