# Copyright Advanced Micro Devices, Inc.
#
# SPDX-License-Identifier: MIT

LIBGV_HW_COMMON_PATH = $(LIBGV_CORE_PATH)/hw/common

LIBGV_HW_COMMON_LOCAL = ras_eeprom_v2_1.o ras_eeprom_legacy.o ras_eeprom_pmme.o

LIBGV_HW_COMMON_FILES = $(LIBGV_HW_COMMON_LOCAL)