/* Copyright Advanced Micro Devices, Inc.
 *
 * SPDX-License-Identifier: MIT
 */


#ifndef __AMDGV_LOG_H__
#define __AMDGV_LOG_H__

#include "amdgv_api.h"


/****************************************************
 * Macro for future extension
 *
 * Current error code is defined in the following:
 * unsigned 32 bits integer
 * bit [0  - 11] are subcode
 * bit [12 - 17] are category
 * bit [18 - 30] are reserved
 * bit [31]      is always 1
 *
 * Current error mask is defined in the following:
 * unsigned 64 bits integer
 * bit [0  -  59] are category mask
 * bit [60  - 63] are severity  level
 *
 ****************************************************/
/* subcode bit length, increase this one if necessary */
#define AMDGV_LOG_SUBCODE_LENGTH  (12)

/* category bit length, should no more than 60 categories, but need 6 bits to hold */
#define AMDGV_LOG_CATEGORY_LENGTH (6)

/* mask category bit length, this is the upper limit of category count */
#define AMDGV_LOG_MASK_CATEGORY_LENGTH (60)

/* mask severity bit length */
#define AMDGV_LOG_MASK_SEVERITY_LENGTH (4)

/* The length of error text should be less than this number. */
#define AMDGV_LOG_MSG_SIZE    (256)

/* The safe length of printing out the full error message to buffer. */
#define AMDGV_LOG_BUF_SAFE_SIZE (AMDGV_LOG_MSG_SIZE + 120)

/* error entry flags */
#define AMDGV_LOG_FLAG_EXT 1

#define AMDGV_LOG_EXT_MAX_ARGS 15

/****************************************************
 * Helper Macro
 ****************************************************/
#define AMDGV_LOG_SUBCODE_MASK   ((1 << AMDGV_LOG_SUBCODE_LENGTH) - 1)
#define AMDGV_LOG_CATEGORY_MASK  ((1 << AMDGV_LOG_CATEGORY_LENGTH) - 1)
#define AMDGV_LOG_CATEGORY_SHIFT AMDGV_LOG_SUBCODE_LENGTH

#define AMDGV_LOG_MASK_SEVERITY_MASK  ((1UL << AMDGV_LOG_MASK_SEVERITY_LENGTH) - 1)
#define AMDGV_LOG_MASK_SEVERITY_SHIFT AMDGV_LOG_MASK_CATEGORY_LENGTH
#define AMDGV_LOG_MASK_CATEGORY_MASK  ((1ULL << AMDGV_LOG_MASK_CATEGORY_LENGTH) - 1)

/* error code MSB should be set to 1 */
#define AMDGV_LOG_CODE(cate, sub) \
	((1<<31) | \
	(((cate) & AMDGV_LOG_CATEGORY_MASK) << AMDGV_LOG_CATEGORY_SHIFT) | \
	((sub) & AMDGV_LOG_SUBCODE_MASK))

#define AMDGV_LOG_CATEGORY(code)     (((code) >> AMDGV_LOG_CATEGORY_SHIFT) & AMDGV_LOG_CATEGORY_MASK)
#define AMDGV_LOG_SUBCODE(code)      ((code) & AMDGV_LOG_SUBCODE_MASK)

#define AMDGV_LOG_MASK_CATEGORY(mask)     ((mask) & AMDGV_LOG_MASK_CATEGORY_MASK)
#define AMDGV_LOG_MASK_SEVERITY(mask)     (((mask) >> AMDGV_LOG_MASK_SEVERITY_SHIFT) & AMDGV_LOG_MASK_SEVERITY_MASK)

#define AMDGV_LOG_DATA_32_32(a, b)  ((((uint64_t)a) << 32) | (((uint64_t)b) & 0xFFFFFFFF))
#define AMDGV_LOG_DATA_16_16_32(a, b, c) ((((uint64_t)a) << 48) | (((uint64_t)b) << 32) | (((uint64_t)c) & 0xFFFFFFFF))
#define AMDGV_LOG_DATA_16_16_16_16(a, b, c, d) ((((uint64_t)a) << 48) | (((uint64_t)b) << 32) |  (((uint64_t)c) << 16) | (((uint64_t)d) & 0xFFFFFFFF))

#define AMDGV_LOG_SYS_MSG_SIZE 512

/****************************************************
 * Function Define and Macro
 ****************************************************/
#define amdgv_put_log(idx_vf, code, data) \
	amdgv_put_event(adapt, idx_vf, code, data, __func__, __LINE__)

#define amdgv_put_log_ext(idx_vf, code, data, ...) \
	amdgv_put_event_ext(adapt, idx_vf, code, data, __func__, __LINE__, __VA_ARGS__)

#define AMDGV_LOG_PRINT_HEADER "%s[%x:%x:%x:%x][%s][%s:%d] "

/*
* define error severity
* ERROR_HIGH : critical error, requires RMA, flash VBIOS or reboot host
* ERROR_MED : important error requires reload GIM, reset whole GPU or VF_FLR
* ERROR_LOW : less significant error requires reboot guest or log only
*        as the action will be performed by driver itself
* WARNING : incorrect event happened but no action is required
* INFO : just notification of occurred event
*/
enum AMDGV_LOG_SEVERITY {
	AMDGV_LOG_SEVERITY_ERROR_HIGH,
	AMDGV_LOG_SEVERITY_ERROR_MED,
	AMDGV_LOG_SEVERITY_ERROR_LOW,
	AMDGV_LOG_SEVERITY_WARNING,
	AMDGV_LOG_SEVERITY_INFO,
	AMDGV_LOG_SEVERITY_DEBUG,
};

enum AMDGV_LOG_RING_TYPE {
	AMDGV_LOG_RING_ERROR = 0,
	AMDGV_LOG_RING_INFO,
	AMDGV_LOG_RING_DEBUG,
	AMDGV_LOG_RING_TYPE_MAX,
};

/*
 * Please add your new cateogry at the end of this enum
 * Remember to update amdgv_log_list
 * in amdgv_log_subcode.c
 */
enum AMDGV_LOG_CATEGORY {
	AMDGV_LOG_CATEGORY_NON_USED = 0,
	AMDGV_LOG_CATEGORY_DRIVER   = 1,
	AMDGV_LOG_CATEGORY_RESET    = 2,
	AMDGV_LOG_CATEGORY_SCHED    = 3,
	AMDGV_LOG_CATEGORY_VBIOS    = 4,
	AMDGV_LOG_CATEGORY_ECC      = 5,
	AMDGV_LOG_CATEGORY_PP       = 6,
	AMDGV_LOG_CATEGORY_IOV      = 7,
	AMDGV_LOG_CATEGORY_VF       = 8,
	AMDGV_LOG_CATEGORY_FW       = 9,
	AMDGV_LOG_CATEGORY_GPU      = 10,
	AMDGV_LOG_CATEGORY_GUARD    = 11,
	AMDGV_LOG_CATEGORY_GPUMON   = 12,
	AMDGV_LOG_CATEGORY_MMSCH    = 13,
	AMDGV_LOG_CATEGORY_XGMI     = 14,

	AMDGV_LOG_CATEGORY_MAX // Max category size is currently 2**6 which is 64 in total
};

#define AMDGV_START_SUBCODE(cate) AMDGV_LOG_CODE(AMDGV_LOG_CATEGORY_ ## cate, 0)

/*
 * Below are the error subcodes of each category.
 * Remember to populate it in amdgv_log_subcode.c
 */
enum AMDGV_LOG_GPU {
	AMDGV_LOG_GPU_DEVICE_LOST = AMDGV_START_SUBCODE(GPU),
	AMDGV_LOG_GPU_NOT_SUPPORTED,
	AMDGV_LOG_GPU_RMA,
	AMDGV_LOG_GPU_NOT_INITIALIZED,
	AMDGV_LOG_GPU_MMSCH_ABNORMAL_STATE,
	AMDGV_LOG_GPU_RLCV_ABNORMAL_STATE,
	AMDGV_LOG_GPU_SDMA_ENGINE_BUSY,
	AMDGV_LOG_GPU_RLC_ENGINE_BUSY,
	AMDGV_LOG_GPU_GC_ENGINE_BUSY,
	AMDGV_LOG_GPU_HIVE_RMA,
	AMDGV_LOG_GPU_UTCL2_BUSY,
	AMDGV_LOG_GPU_UTCL2_HANG,
	AMDGV_LOG_GPU_GL2C_ERROR_DETECTED,
	AMDGV_LOG_GPU_GC_SOFT_RESET_VMID_TIMEOUT,

	AMDGV_LOG_GPU_MAX
};


enum AMDGV_LOG_DRIVER {
	AMDGV_LOG_DRIVER_SPIN_LOCK_BUSY = AMDGV_START_SUBCODE(DRIVER),
	AMDGV_LOG_DRIVER_ALLOC_SYSTEM_MEM_FAIL,
	AMDGV_LOG_DRIVER_RESERVE_SYSTEM_MEM_FAIL,
	AMDGV_LOG_DRIVER_CREATE_GFX_WORKQUEUE_FAIL,
	AMDGV_LOG_DRIVER_CREATE_MM_WORKQUEUE_FAIL,
	AMDGV_LOG_DRIVER_BUFFER_OVERFLOW,

	AMDGV_LOG_DRIVER_DEV_INIT_FAIL,
	AMDGV_LOG_DRIVER_CREATE_THREAD_FAIL,
	AMDGV_LOG_DRIVER_NO_ACCESS_PCI_REGION,
	AMDGV_LOG_DRIVER_MMIO_FAIL,
	AMDGV_LOG_DRIVER_INTERRUPT_INIT_FAIL,

	AMDGV_LOG_DRIVER_INVALID_VALUE,
	AMDGV_LOG_DRIVER_CREATE_MUTEX_FAIL,
	AMDGV_LOG_DRIVER_CREATE_TIMER_FAIL,
	AMDGV_LOG_DRIVER_CREATE_EVENT_FAIL,
	AMDGV_LOG_DRIVER_CREATE_SPIN_LOCK_FAIL,

	AMDGV_LOG_DRIVER_ALLOC_FB_MEM_FAIL,
	AMDGV_LOG_DRIVER_ALLOC_DMA_MEM_FAIL,
	AMDGV_LOG_DRIVER_MAP_DMA_MEM_FAIL,
	AMDGV_LOG_DRIVER_NO_FB_MANAGER,
	AMDGV_LOG_DRIVER_HW_INIT_FAIL,
	AMDGV_LOG_DRIVER_SW_INIT_FAIL,

	AMDGV_LOG_DRIVER_INIT_CONFIG_ERROR,
	AMDGV_LOG_DRIVER_ERROR_LOGGING_FAILED,
	AMDGV_LOG_DRIVER_CREATE_RWLOCK_FAIL,
	AMDGV_LOG_DRIVER_CREATE_RWSEMA_FAIL,
	AMDGV_LOG_DRIVER_GET_READ_LOCK_FAIL,

	AMDGV_LOG_DRIVER_GET_WRITE_LOCK_FAIL,
	AMDGV_LOG_DRIVER_GET_READ_SEMA_FAIL,
	AMDGV_LOG_DRIVER_GET_WRITE_SEMA_FAIL,

	AMDGV_LOG_DRIVER_DIAG_DATA_INIT_FAIL,
	AMDGV_LOG_DRIVER_DIAG_DATA_MEM_REQ_FAIL,
	AMDGV_LOG_DRIVER_DIAG_DATA_VADDR_REQ_FAIL,
	AMDGV_LOG_DRIVER_DIAG_DATA_BUS_ADDR_REQ_FAIL,

	AMDGV_LOG_DRIVER_HRTIMER_START_FAIL,
	AMDGV_LOG_DRIVER_CREATE_DRIVER_FILE_FAIL,
	AMDGV_LOG_DRIVER_CREATE_DEVICE_FILE_FAIL,
	AMDGV_LOG_DRIVER_CREATE_DEBUGFS_FILE_FAIL,
	AMDGV_LOG_DRIVER_CREATE_DEBUGFS_DIR_FAIL,

	AMDGV_LOG_DRIVER_PCI_ENABLE_DEVICE_FAIL,
	AMDGV_LOG_DRIVER_FB_MAP_FAIL,
	AMDGV_LOG_DRIVER_DOORBELL_MAP_FAIL,
	AMDGV_LOG_DRIVER_PCI_REGISTER_DRIVER_FAIL,
	AMDGV_LOG_DRIVER_VF_RESIZE_BAR_FAIL,

	AMDGV_LOG_DRIVER_ALLOC_IOVA_ALIGN_FAIL,
	AMDGV_LOG_DRIVER_SET_MEM_ATTRIBUTE_FAIL,
	AMDGV_LOG_DRIVER_FIND_ADDR_PTE_FAIL,
	AMDGV_LOG_DRIVER_ALLOC_SG_FAIL,

	AMDGV_LOG_DRIVER_ROM_MAP_FAIL,

	AMDGV_LOG_DRIVER_FULL_ACCESS_TIMEOUT,

	AMDGV_LOG_DRIVER_MIGRATION_INIT_FAIL,
	AMDGV_LOG_DRIVER_MIGRATION_GET_MIG_INFO_FAIL,
	AMDGV_LOG_DRIVER_MIGRATION_THREAD_INIT_FAIL,
	AMDGV_LOG_DRIVER_MIGRATION_SETUP_ENV_FAIL,
	AMDGV_LOG_DRIVER_MIGRATION_DATA_COPY_FAIL,
	AMDGV_LOG_DRIVER_MIGRATION_IMPORT_FAIL,
	AMDGV_LOG_DRIVER_MIGRATION_EXPORT_FAIL,
	AMDGV_LOG_DRIVER_PCIE_CAP_MISSING,
	AMDGV_LOG_DRIVER_REGISTER_INTERRUPT_FAIL,
	AMDGV_LOG_DRIVER_HBM_MGMT_INIT_FAIL,
	AMDGV_LOG_DRIVER_PF_FB_SIZE,
	AMDGV_LOG_DRIVER_FB_APERTURE_SIZE,
	AMDGV_LOG_DRIVER_FB_BLOCK_SIZE_ZERO,
	AMDGV_LOG_DRIVER_NO_FREE_FB_BLOCK,
	AMDGV_LOG_DRIVER_PF_FB_RECONFIG_DENIED,
	AMDGV_LOG_DRIVER_FB_SIZE_UNALIGNED,
	AMDGV_LOG_DRIVER_ASYMMETRIC_FB_NOT_SUPPORTED,
	AMDGV_LOG_DRIVER_ACTIVE_VF_FB_CHANGE_DENIED,
	AMDGV_LOG_DRIVER_VF_FB_RECONFIG_FAIL,
	AMDGV_LOG_DRIVER_FFBM_VF_FB_TMR_LAYOUT,
	AMDGV_LOG_DRIVER_IPD_FB_SIZE_MISMATCH,
	AMDGV_LOG_DRIVER_TOTAL_VF_FB_SIZE,
	AMDGV_LOG_DRIVER_VF_FB_LAYOUT,
	AMDGV_LOG_DRIVER_ACTIVE_VF_DETECTED,
	AMDGV_LOG_DRIVER_SERVICE_VM_ENABLED,
	AMDGV_LOG_DRIVER_VF_MGMT_MODE,
	AMDGV_LOG_DRIVER_ENABLED_VF_NUM,
	AMDGV_LOG_DRIVER_LIVE_UPDATE_SLOT_OVERFLOW,

	AMDGV_LOG_DRIVER_MAX
};


enum AMDGV_LOG_FW {
	AMDGV_LOG_FW_CMD_ALLOC_BUF_FAIL = AMDGV_START_SUBCODE(FW),
	AMDGV_LOG_FW_CMD_BUF_PREP_FAIL,
	AMDGV_LOG_FW_RING_INIT_FAIL,
	AMDGV_LOG_FW_UCODE_APPLY_SECURITY_POLICY_FAIL,
	AMDGV_LOG_FW_START_RING_FAIL,

	AMDGV_LOG_FW_UCODE_LOAD_FAIL,
	AMDGV_LOG_FW_EXIT_FAIL,
	AMDGV_LOG_FW_INIT_FAIL,
	AMDGV_LOG_FW_CMD_SUBMIT_FAIL,
	AMDGV_LOG_FW_CMD_FENCE_WAIT_FAIL,

	AMDGV_LOG_FW_TMR_LOAD_FAIL,
	AMDGV_LOG_FW_TOC_LOAD_FAIL,
	AMDGV_LOG_FW_RAS_LOAD_FAIL,
	AMDGV_LOG_FW_RAS_UNLOAD_FAIL,
	AMDGV_LOG_FW_RAS_TA_INVOKE_FAIL,
	AMDGV_LOG_FW_RAS_TA_ERR_INJECT_FAIL,
	AMDGV_LOG_FW_RAS_TA_ENABLE_RAS_FEATURE_FAIL,

	AMDGV_LOG_FW_ASD_LOAD_FAIL,
	AMDGV_LOG_FW_ASD_UNLOAD_FAIL,
	AMDGV_LOG_FW_AUTOLOAD_FAIL,
	AMDGV_LOG_FW_VFGATE_FAIL,
	AMDGV_LOG_FW_XGMI_LOAD_FAIL,

	AMDGV_LOG_FW_XGMI_UNLOAD_FAIL,
	AMDGV_LOG_FW_XGMI_TA_INVOKE_FAIL,

	AMDGV_LOG_FW_TMR_INIT_FAIL,
	AMDGV_LOG_FW_NOT_SUPPORTED_FEATURE,
	AMDGV_LOG_FW_GET_PSP_TRACELOG_FAIL,

	AMDGV_LOG_FW_SET_SNAPSHOT_ADDR_FAIL,
	AMDGV_LOG_FW_SNAPSHOT_TRIGGER_FAIL,

	AMDGV_LOG_FW_MIGRATION_GET_PSP_INFO_FAIL,
	AMDGV_LOG_FW_MIGRATION_EXPORT_FAIL,
	AMDGV_LOG_FW_MIGRATION_IMPORT_FAIL,

	AMDGV_LOG_FW_BL_FAIL,
	AMDGV_LOG_FW_RAS_BOOT_FAIL,

	AMDGV_LOG_FW_MAILBOX_ERROR,

	AMDGV_LOG_FW_RAS_MEM_TRAIN_FAIL,
	AMDGV_LOG_FW_RAS_FW_LOAD_FAIL,
	AMDGV_LOG_FW_RAS_WAFL_LINK_TRAIN_FAIL,
	AMDGV_LOG_FW_RAS_XGMI_LINK_TRAIN_FAIL,
	AMDGV_LOG_FW_RAS_USR_CP_LINK_TRAIN_FAIL,
	AMDGV_LOG_FW_RAS_USR_DP_LINK_TRAIN_FAIL,
	AMDGV_LOG_FW_RAS_HBM_MEM_TEST_FAIL,
	AMDGV_LOG_FW_RAS_HBM_BIST_TEST_FAIL,
	AMDGV_LOG_FW_RAS_BOOT_REG_READ_FAIL,

	AMDGV_LOG_FW_MIGRATION_VF_CP_NOT_SUPPORTED,
	AMDGV_LOG_FW_MIGRATION_GET_DATA_SIZE_FAIL,
	AMDGV_LOG_FW_MIGRATION_DATA_OVERSIZE,
	AMDGV_LOG_FW_MIGRATION_AUTOLOAD_FAIL,
	AMDGV_LOG_FW_SMU_NOT_RESPONDING,
	AMDGV_LOG_FW_TRIGGER_VF_FLR_FAIL,
	AMDGV_LOG_FW_TRIGGER_VF_FLR_NOT_IMPLEMENTED,

	AMDGV_LOG_FW_MAX
};


enum AMDGV_LOG_RESET {
	AMDGV_LOG_RESET_GPU = AMDGV_START_SUBCODE(RESET),
	AMDGV_LOG_RESET_GPU_FAILED,
	AMDGV_LOG_RESET_FLR,
	AMDGV_LOG_RESET_FLR_FAILED,
	AMDGV_LOG_RESET_GPU_HIVE_FAILED,
	AMDGV_LOG_RESET_PF_SOFT_FLR_DONE,
	AMDGV_LOG_RESET_NOTIFY_VF,
	AMDGV_LOG_RESET_NOTIFY_VF_COMPLETION,
	AMDGV_LOG_RESET_PROGRAM_VF_MC_SETTINGS,
	AMDGV_LOG_RESET_FLR_SET_ACC_BITS_DIRTY,
	AMDGV_LOG_RESET_FLR_DISABLED,
	AMDGV_LOG_RESET_FLR_DONE,
	AMDGV_LOG_RESET_DROP_ORPHAN_REQUEST,
	AMDGV_LOG_RESET_FLR_START,
	AMDGV_LOG_RESET_FLR_RLC_IDLE_FAIL,
	AMDGV_LOG_RESET_FLR_TRANS_PENDING,
	AMDGV_LOG_RESET_FLR_GRBM_DIRTY,
	AMDGV_LOG_RESET_FLR_GRBM_NOT_CLEAN,
	AMDGV_LOG_RESET_PF_FLR_NOT_SUPPORTED,
	AMDGV_LOG_RESET_PF_FLR_SHARED_XCC_MASK,
	AMDGV_LOG_RESET_GPU_DONE,

	AMDGV_LOG_RESET_GPU_CONFIG_CHANGE,
	AMDGV_LOG_RESET_GPU_UNLOAD,
	AMDGV_LOG_RESET_GPU_RELOAD,

	AMDGV_LOG_RESET_MAX
};


enum AMDGV_LOG_IOV {
	AMDGV_LOG_IOV_NO_GPU_IOV_CAP = AMDGV_START_SUBCODE(IOV),
	AMDGV_LOG_IOV_ASIC_NO_SRIOV_SUPPORT,
	AMDGV_LOG_IOV_ENABLE_SRIOV_FAIL,
	AMDGV_LOG_IOV_CMD_TIMEOUT,
	AMDGV_LOG_IOV_CMD_ERROR,

	AMDGV_LOG_IOV_INIT_IV_RING_FAIL,
	AMDGV_LOG_IOV_SRIOV_STRIDE_ERROR,
	AMDGV_LOG_IOV_WS_SAVE_TIMEOUT,
	AMDGV_LOG_IOV_WS_IDLE_TIMEOUT,
	AMDGV_LOG_IOV_WS_RUN_TIMEOUT,
	AMDGV_LOG_IOV_WS_LOAD_TIMEOUT,
	AMDGV_LOG_IOV_WS_SHUTDOWN_TIMEOUT,
	AMDGV_LOG_IOV_WS_ALREADY_SHUTDOWN,
	AMDGV_LOG_IOV_WS_INFINITE_LOOP,
	AMDGV_LOG_IOV_WS_REENTRANT_ERROR,
	AMDGV_LOG_IOV_LIVE_MIGRATION_EXPORT_STATIC,
	AMDGV_LOG_IOV_LIVE_MIGRATION_EXPORT_DYNAMIC,
	AMDGV_LOG_IOV_LIVE_MIGRATION_IMPORT_PREPARE,
	AMDGV_LOG_IOV_LIVE_MIGRATION_IMPORT_STATIC,
	AMDGV_LOG_IOV_LIVE_MIGRATION_IMPORT_DYNAMIC,
	AMDGV_LOG_IOV_LIVE_MIGRATION_EXPORT_STATIC_FAILED,
	AMDGV_LOG_IOV_LIVE_MIGRATION_EXPORT_DYNAMIC_FAILED,
	AMDGV_LOG_IOV_LIVE_MIGRATION_IMPORT_PREPARE_FAILED,
	AMDGV_LOG_IOV_LIVE_MIGRATION_IMPORT_STATIC_FAILED,
	AMDGV_LOG_IOV_LIVE_MIGRATION_IMPORT_DYNAMIC_FAILED,

	AMDGV_LOG_IOV_EVENT_NOTIFICATION_NOT_SUPPORTED,
	AMDGV_LOG_IOV_CSA_FB_MEM_NOT_ALLOCATED,
	AMDGV_LOG_IOV_READ_VF_FB_FAIL,
	AMDGV_LOG_IOV_L1_SECURITY_DISABLED,
	AMDGV_LOG_IOV_MB_MSG_BUF_NOT_ALLOCATED,
	AMDGV_LOG_IOV_MB_INVALID_IDX,
	AMDGV_LOG_IOV_MB_MSG_TOO_LONG,
	AMDGV_LOG_IOV_MB_NOTIFY_GPU_DEBUG,
	AMDGV_LOG_IOV_MB_IRQ_SOURCE_ENABLE_FAIL,
	AMDGV_LOG_IOV_IH_RING_NOT_ALLOCATED,
	AMDGV_LOG_IOV_IH_QUEUE_FULL,
	AMDGV_LOG_IOV_MB_INVALID_VF_EVENT,
	AMDGV_LOG_IOV_PSP_VF_CMD_RELAY_OUT_OF_RANGE,
	AMDGV_LOG_IOV_UNSUPPORTED_CRIT_REGION_VER,
	AMDGV_LOG_IOV_UNHANDLED_HV_INTR,
	AMDGV_LOG_IOV_IP_DISCOVERY_UPLOAD_FAIL,
	AMDGV_LOG_IOV_CPER_RECORD_OVERFLOW,
	AMDGV_LOG_IOV_UNSUPPORTED_CPER_EVENT,
	AMDGV_LOG_IOV_CRIT_REGION_NOT_INITIALIZED,
	AMDGV_LOG_IOV_BAD_PAGE_IN_CRIT_REGION,
	AMDGV_LOG_IOV_CRIT_REGION_V1_DISABLED_BAD_PAGE,
	AMDGV_LOG_IOV_CRIT_REGION_BP_RESERVE_FAIL,
	AMDGV_LOG_IOV_CRIT_REGION_TABLE_ALLOC_FAIL,
	AMDGV_LOG_IOV_CRIT_REGION_INIT_FAIL,
	AMDGV_LOG_IOV_VF2PF_CHECKSUM_MISMATCH,
	AMDGV_LOG_IOV_VF2PF_UNTRUSTWORTHY_GUEST_INFO,
	AMDGV_LOG_IOV_UPLOAD_FW_XCHG_DENIED,
	AMDGV_LOG_IOV_MMIO_VF_NOT_CONFIGURED,
	AMDGV_LOG_IOV_MMIO_VF_RES_NOT_MAPPED,
	AMDGV_LOG_IOV_GUEST_DRIVER_LOAD_DETECTED,
	AMDGV_LOG_IOV_ARBITRARY_VF_MEM_ACCESS_DENIED,
	AMDGV_LOG_IOV_INVALID_CRIT_REGION_VER,
	AMDGV_LOG_IOV_UPLOAD_FW_TO_VF_FAIL,
	AMDGV_LOG_IOV_BAD_PAGE_CRIT_REGION_COND_AVAIL,

	AMDGV_LOG_IOV_MAX
};


enum AMDGV_LOG_ECC {
	AMDGV_LOG_ECC_UCE = AMDGV_START_SUBCODE(ECC),
	AMDGV_LOG_ECC_CE,
	AMDGV_LOG_ECC_IN_PF_FB,
	AMDGV_LOG_ECC_IN_CRI_REG,
	AMDGV_LOG_ECC_IN_VF_CRI,
	AMDGV_LOG_ECC_REACH_THD,
	AMDGV_LOG_ECC_VF_CE,
	AMDGV_LOG_ECC_VF_UE,
	AMDGV_LOG_ECC_IN_SAME_ROW,
	AMDGV_LOG_ECC_UMC_UE,
	AMDGV_LOG_ECC_GFX_CE,
	AMDGV_LOG_ECC_GFX_UE,
	AMDGV_LOG_ECC_SDMA_CE,
	AMDGV_LOG_ECC_SDMA_UE,
	AMDGV_LOG_ECC_GFX_CE_TOTAL,
	AMDGV_LOG_ECC_GFX_UE_TOTAL,
	AMDGV_LOG_ECC_SDMA_CE_TOTAL,
	AMDGV_LOG_ECC_SDMA_UE_TOTAL,
	AMDGV_LOG_ECC_UMC_CE_TOTAL,
	AMDGV_LOG_ECC_UMC_UE_TOTAL,
	AMDGV_LOG_ECC_MMHUB_CE,
	AMDGV_LOG_ECC_MMHUB_UE,
	AMDGV_LOG_ECC_MMHUB_CE_TOTAL,
	AMDGV_LOG_ECC_MMHUB_UE_TOTAL,
	AMDGV_LOG_ECC_XGMI_WAFL_CE,
	AMDGV_LOG_ECC_XGMI_WAFL_UE,
	AMDGV_LOG_ECC_XGMI_WAFL_CE_TOTAL,
	AMDGV_LOG_ECC_XGMI_WAFL_UE_TOTAL,
	AMDGV_LOG_ECC_FATAL_ERROR,
	AMDGV_LOG_ECC_POISON_CONSUMPTION,
	AMDGV_LOG_ECC_ACA_DUMP,
	AMDGV_LOG_ECC_WRONG_SOCKET_ID,
	AMDGV_LOG_ECC_ACA_UNKNOWN_BLOCK_INSTANCE,
	AMDGV_LOG_ECC_UNKNOWN_CHIPLET_CE,
	AMDGV_LOG_ECC_UNKNOWN_CHIPLET_UE,
	AMDGV_LOG_ECC_UMC_CHIPLET_CE,
	AMDGV_LOG_ECC_UMC_CHIPLET_UE,
	AMDGV_LOG_ECC_GFX_CHIPLET_CE,
	AMDGV_LOG_ECC_GFX_CHIPLET_UE,
	AMDGV_LOG_ECC_SDMA_CHIPLET_CE,
	AMDGV_LOG_ECC_SDMA_CHIPLET_UE,
	AMDGV_LOG_ECC_MMHUB_CHIPLET_CE,
	AMDGV_LOG_ECC_MMHUB_CHIPLET_UE,
	AMDGV_LOG_ECC_XGMI_WAFL_CHIPLET_CE,
	AMDGV_LOG_ECC_XGMI_WAFL_CHIPLET_UE,
	AMDGV_LOG_ECC_BAD_PAGE_ENTRIES_FOUND,
	AMDGV_LOG_ECC_UMC_DE,
	AMDGV_LOG_ECC_UMC_DE_TOTAL,
	AMDGV_LOG_ECC_UNKNOWN,
	AMDGV_LOG_ECC_EEPROM_REACH_THD,
	AMDGV_LOG_ECC_UMC_CHIPLET_DE,
	AMDGV_LOG_ECC_UNKNOWN_CHIPLET_DE,
	AMDGV_LOG_ECC_EEPROM_CHK_MISMATCH,
	AMDGV_LOG_ECC_EEPROM_RESET,
	AMDGV_LOG_ECC_EEPROM_RESET_FAILED,
	AMDGV_LOG_ECC_EEPROM_APPEND,
	AMDGV_LOG_ECC_THD_CHANGED,
	AMDGV_LOG_ECC_DUP_ENTRIES,
	AMDGV_LOG_ECC_EEPROM_WRONG_HDR,
	AMDGV_LOG_ECC_EEPROM_WRONG_VER,
	AMDGV_LOG_ECC_BAD_PAGE_APPEND,
	AMDGV_LOG_ECC_VCN_CHIPLET_CE,
	AMDGV_LOG_ECC_VCN_CHIPLET_UE,
	AMDGV_LOG_ECC_JPEG_CHIPLET_CE,
	AMDGV_LOG_ECC_JPEG_CHIPLET_UE,
	AMDGV_LOG_ECC_EEPROM_VERSION_PARSE_FAILED,
	AMDGV_LOG_ECC_EEPROM_CONFIG_BP_THD_NOT_SUPPORTED,
	AMDGV_LOG_ECC_MMSCH_CHIPLET_CE,
	AMDGV_LOG_ECC_MMSCH_CHIPLET_UE,
	AMDGV_LOG_ECC_MAX
};


enum AMDGV_LOG_PP {
	AMDGV_LOG_PP_SET_DPM_POLICY_FAIL = AMDGV_START_SUBCODE(PP),
	AMDGV_LOG_PP_ACTIVATE_DPM_POLICY_FAIL,
	AMDGV_LOG_PP_I2C_SLAVE_NOT_PRESENT,
	AMDGV_LOG_PP_THROTTLER_EVENT,
	AMDGV_LOG_PP_MODE2_RESET_FAIL,
	AMDGV_LOG_PP_MODE0_RESET_FAIL,

	AMDGV_LOG_PP_MAX
};


enum AMDGV_LOG_SCHED {
	AMDGV_LOG_SCHED_WORLD_SWITCH_FAIL = AMDGV_START_SUBCODE(SCHED),
	AMDGV_LOG_SCHED_DISABLE_AUTO_HW_SWITCH_FAIL,
	AMDGV_LOG_SCHED_ENABLE_AUTO_HW_SWITCH_FAIL,
	AMDGV_LOG_SCHED_GFX_SAVE_REG_FAIL,
	AMDGV_LOG_SCHED_GFX_IDLE_REG_FAIL,

	AMDGV_LOG_SCHED_GFX_RUN_REG_FAIL,
	AMDGV_LOG_SCHED_GFX_LOAD_REG_FAIL,
	AMDGV_LOG_SCHED_GFX_INIT_REG_FAIL,
	AMDGV_LOG_SCHED_MM_SAVE_REG_FAIL,
	AMDGV_LOG_SCHED_MM_IDLE_REG_FAIL,

	AMDGV_LOG_SCHED_MM_RUN_REG_FAIL,
	AMDGV_LOG_SCHED_MM_LOAD_REG_FAIL,
	AMDGV_LOG_SCHED_MM_INIT_REG_FAIL,
	AMDGV_LOG_SCHED_INIT_GPU_FAIL,
	AMDGV_LOG_SCHED_RUN_GPU_FAIL,

	AMDGV_LOG_SCHED_SAVE_GPU_STATE_FAIL,
	AMDGV_LOG_SCHED_LOAD_GPU_STATE_FAIL,
	AMDGV_LOG_SCHED_IDLE_GPU_FAIL,
	AMDGV_LOG_SCHED_FINI_GPU_FAIL,
	AMDGV_LOG_SCHED_DEAD_VF,

	AMDGV_LOG_SCHED_EVENT_QUEUE_FULL,
	AMDGV_LOG_SCHED_SHUTDOWN_VF_FAIL,
	AMDGV_LOG_SCHED_RESET_VF_NUM_FAIL,
	AMDGV_LOG_SCHED_IGNORE_EVENT,
	AMDGV_LOG_SCHED_PF_SWITCH_FAIL,

	AMDGV_LOG_SCHED_INVALID_HW_SCHED_ID,
	AMDGV_LOG_SCHED_AUTO_SCHED_STOP_TIMEOUT,
	AMDGV_LOG_SCHED_RLCG_VF_INTF_FAIL,
	AMDGV_LOG_SCHED_GFX_MODE_NOT_SUPPORTED,
	AMDGV_LOG_SCHED_INVALID_XCC_NUM,
	AMDGV_LOG_SCHED_PARTITION_FULL_ACCESS_DISABLED,
	AMDGV_LOG_SCHED_FULL_ACCESS_TIME_CHANGED,
	AMDGV_LOG_SCHED_SET_VF_FB,
	AMDGV_LOG_SCHED_CTX_EMPTY_INTR_GATE,
	AMDGV_LOG_SCHED_LIVE_MIGRATION_NOT_SUPPORTED,
	AMDGV_LOG_SCHED_NO_ABNORMAL_ENGINE,
	AMDGV_LOG_SCHED_RESET_AUTO_ENGINE_HUNG,
	AMDGV_LOG_SCHED_PF_HUNG_WGR,
	AMDGV_LOG_SCHED_HUNG_ENGINE_INVALID_VF,
	AMDGV_LOG_SCHED_HW_SCHED_NO_LOGICAL,

	AMDGV_LOG_SCHED_MAX
};


enum AMDGV_LOG_VF {
	AMDGV_LOG_VF_ATOMBIOS_INIT_FAIL = AMDGV_START_SUBCODE(VF),
	AMDGV_LOG_VF_NO_VBIOS,
	AMDGV_LOG_VF_GPU_POST_ERROR,
	AMDGV_LOG_VF_ATOMBIOS_GET_CLOCK_FAIL,
	AMDGV_LOG_VF_FENCE_INIT_FAIL,

	AMDGV_LOG_VF_AMDGPU_INIT_FAIL,
	AMDGV_LOG_VF_IB_INIT_FAIL,
	AMDGV_LOG_VF_AMDGPU_LATE_INIT_FAIL,
	AMDGV_LOG_VF_ASIC_RESUME_FAIL,
	AMDGV_LOG_VF_GPU_RESET_FAIL,
	AMDGV_LOG_VF_XCHG_REGION_INVALID_SIZE,
	AMDGV_LOG_VF_XCHG_REGION_NOT_INITIALIZED,
	AMDGV_LOG_VF_XCHG_TABLE_TARGET_INVALID,

	AMDGV_LOG_VF_MAX
};


enum AMDGV_LOG_VBIOS {
	AMDGV_LOG_VBIOS_INVALID = AMDGV_START_SUBCODE(VBIOS),
	AMDGV_LOG_VBIOS_IMAGE_MISSING,
	AMDGV_LOG_VBIOS_CHECKSUM_ERR,
	AMDGV_LOG_VBIOS_POST_FAIL,
	AMDGV_LOG_VBIOS_READ_FAIL,

	AMDGV_LOG_VBIOS_READ_IMG_HEADER_FAIL,
	AMDGV_LOG_VBIOS_READ_IMG_SIZE_FAIL,
	AMDGV_LOG_VBIOS_GET_FW_INFO_FAIL,
	AMDGV_LOG_VBIOS_GET_TBL_REVISION_FAIL,
	AMDGV_LOG_VBIOS_PARSER_TBL_FAIL,

	AMDGV_LOG_VBIOS_IP_DISCOVERY_FAIL,
	AMDGV_LOG_VBIOS_TIMEOUT,

	AMDGV_LOG_VBIOS_IP_DISCOVERY_BINARY_CHECKSUM_FAIL,
	AMDGV_LOG_VBIOS_IP_DISCOVERY_TABLE_CHECKSUM_FAIL,
	AMDGV_LOG_VBIOS_MAX
};

enum AMDGV_LOG_GUARD {
	AMDGV_LOG_GUARD_RESET_FAIL = AMDGV_START_SUBCODE(GUARD),
	AMDGV_LOG_GUARD_EVENT_OVERFLOW,

	AMDGV_LOG_GUARD_MAX
};

enum AMDGV_LOG_GPUMON {
	AMDGV_LOG_GPUMON_INVALID_OPTION = AMDGV_START_SUBCODE(GPUMON),
	AMDGV_LOG_GPUMON_INVALID_VF_INDEX,
	AMDGV_LOG_GPUMON_INVALID_FB_SIZE,
	AMDGV_LOG_GPUMON_NO_SUITABLE_SPACE,
	AMDGV_LOG_GPUMON_NO_AVAILABLE_SLOT,

	AMDGV_LOG_GPUMON_OVERSIZE_ALLOCATION,
	AMDGV_LOG_GPUMON_OVERLAPPING_FB,
	AMDGV_LOG_GPUMON_INVALID_GFX_TIMESLICE,
	AMDGV_LOG_GPUMON_INVALID_MM_TIMESLICE,
	AMDGV_LOG_GPUMON_INVALID_GFX_PART,

	AMDGV_LOG_GPUMON_VF_BUSY,
	AMDGV_LOG_GPUMON_INVALID_VF_NUM,
	AMDGV_LOG_GPUMON_NOT_SUPPORTED,
	AMDGV_LOG_GPUMON_SET_ALREADY,
	AMDGV_LOG_GPUMON_INVALID_MODE,

	AMDGV_LOG_GPUMON_FB_INFO,

	AMDGV_LOG_GPUMON_MAX
};

enum AMDGV_LOG_MMSCH {
	AMDGV_LOG_MMSCH_IGNORED_JOB = AMDGV_START_SUBCODE(MMSCH),
	AMDGV_LOG_MMSCH_UNSUPPORTED_VCN_FW,

	AMDGV_LOG_MMSCH_MAX
};

enum AMDGV_LOG_XGMI {
	AMDGV_LOG_XGMI_TOPOLOGY_UPDATE_FAILED = AMDGV_START_SUBCODE(XGMI),
	AMDGV_LOG_XGMI_TOPOLOGY_HW_INIT_UPDATE,
	AMDGV_LOG_XGMI_TOPOLOGY_UPDATE_DONE,
	AMDGV_LOG_XGMI_FB_SHARING_SETTING_ERROR,
	AMDGV_LOG_XGMI_FB_SHARING_SETTING_RESET,
	AMDGV_LOG_XGMI_CHAIN_RESET_NOTIFY,
	AMDGV_LOG_XGMI_CHAIN_RESET_NOTIFY_FAILED,

	AMDGV_LOG_XGMI_MAX
};

enum amdgv_bp_msg_type {
	AMDGV_BP_MSG_INVALID,
	AMDGV_BP_MSG_IN_PF_FB,
	AMDGV_BP_MSG_IN_CRITICAL_REGION,
	AMDGV_BP_MSG_IN_VF_CRITICAL_REGION,
	AMDGV_BP_MSG_IN_SAME_ROW,
	AMDGV_BP_MSG_RECORD_THRESHOLD_REACHED,
};

enum amdgv_pp_throttler_event {
	AMDGV_PP_THROTTLER_EVENT__PROCHOT = 0,
	AMDGV_PP_THROTTLER_EVENT__SOCKET,
	AMDGV_PP_THROTTLER_EVENT__VR,
	AMDGV_PP_THROTTLER_EVENT__HBM,
};

#undef AMDGV_START_SUBCODE

/**
 * Information captured for each error from a SR-IOV GPU device
 *
 * @timestamp: Time stamp (in nanoseconds) when the error happened
 * @log_code: unique error code that describes the type of error. This
 *  numeric code can be used as an index into a string table to obtain
 *  a human readable description of the error. The high 4 bits indicates the
 *  error category, such as GIM, PF, VF, VBIOS, etc. The low 12 bits indicates
 * the error index in the sub-category error text list.
 * @log_level: indicates the severity of the error
 * @vf_idx: PF or VF function_index
 * @log_data: Data value associated with the specific error.
 * @log_location: Code address where the error was originally captured.
 */
struct amdgv_log_entry {
	uint64_t timestamp;
	uint32_t log_code;
	uint8_t  log_level;
	uint32_t log_flags;
	uint32_t vf_idx;
	uint64_t log_data;
	uint64_t log_location;
	uint64_t log_data_ext[AMDGV_LOG_EXT_MAX_ARGS];
};

struct amdgv_log_notifier;
struct amdgv_adapter;

static const int default_filter_table[] = {
	AMDGV_LOG_IOV_CMD_TIMEOUT,
	AMDGV_LOG_RESET_FLR,
};

int amdgv_log_get_text(uint32_t log_code, uint64_t data, char *buf, uint32_t size);
int amdgv_log_get_text_ext(uint32_t log_code, uint64_t data, char *buf, uint32_t size, uint64_t *data_ext);

void amdgv_put_event(amdgv_dev_t dev, uint32_t idx_vf, uint32_t log_code,
		     uint64_t log_data, const char *func_name, uint32_t line_num);
void amdgv_put_event_ext(amdgv_dev_t dev, uint32_t idx_vf, uint32_t log_code,
		     uint64_t log_data, const char *func_name, uint32_t line_num, ...);

int amdgv_log_get_entry(amdgv_dev_t dev, struct amdgv_log_notifier *notifier,
			struct amdgv_log_entry **log_entry);

int amdgv_log_get_all(struct amdgv_adapter *adapt, char *buf, int len);
int amdgv_log_dump_ring(struct amdgv_adapter *adapt, enum AMDGV_LOG_RING_TYPE ring_type,
			char *buf, int len);
int amdgv_log_dump_combined(struct amdgv_adapter *adapt, char *buf, int len);
int amdgv_log_is_pending(amdgv_dev_t dev, struct amdgv_log_notifier *notifier);

void amdgv_log_put_test_entry(amdgv_dev_t dev, int category);

int amdgv_log_alloc_new_notifier(amdgv_dev_t dev, uint64_t event_mask, void *priv,
				 struct amdgv_log_notifier **notifier);

void amdgv_log_delete_notifier(amdgv_dev_t dev, struct amdgv_log_notifier *notifier);

int amdgv_log_dump_stack_filter_set(amdgv_dev_t dev, uint32_t code, bool add_enter);
void amdgv_log_initialize_default_filters(amdgv_dev_t dev);

#endif
